### ISSUE TITLE
Make ESAPI configuration XML

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#103]
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on January 21, 2010 08:21:01_

ESAPI config file is in properties format, which makes sense for a Java 
application but if it was in XML, it might be possible to port it to 
applications in .NET, Cold Fusion, etc. So baseline configuration files could 
be created at the same time a simple XSL file could create a nice HTML 
version of the configuration file for purposes like this one.

Jim adds: also consider configuration chaining (where one main xml config 
could load another xml config to allow for config separation between each 
"module", like the castor and other project provide.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=93_

**Comment by kwwall** [comment]
Fixed as part of commit c644f320d1d0f2bad11340845bf55d7747025200. It's crude, but it's there. See documentation/ESAPI-configuration-user-guide.md for details.
