### ISSUE TITLE
Limit max size of entire cookies

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#163]
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on September 28, 2010 19:29:43_

Spec says:

```
  * at least 4096 bytes per cookie (as measured by the size of the
    characters that comprise the cookie non-terminal in the syntax
    description of the Set-Cookie header)
```

So it sounds to me that this is a limitation on the size of the _entire_ cookie including all meta data _and_ name. Thus, if we limit the size of the data to 4096 and someone actually uses all 4096 bytes of space for their data we could be breaking spec with the rest of the headers. 

My gut here is that we should be calculating this as the cookie is built (container implementations may also already be doing this FWIW)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=153_

**Comment by kwwall** [comment]
Two (perhaps useful) links to whomever may wish to work on this:
https://tools.ietf.org/html/rfc6265.html -- especially section 6.1
https://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key

**Comment by kwwall** [comment]
For this, at most, we should log a warning, but I don't think that we otherwise should "interfere" between the application server and the client (usually a web browser), because the 4k is a minimum, not a maximum.

**Comment by kwwall** [comment]
@xeno6696 - In classes `HTTPUtilities` / `DefaultHTTPUtilities`, there already seems to be an implementation for this with checks against `HTTPUtilities.MAX_COOKIE_LEN`. Could you take a look and see if you concur and if so, close this issue? If that doesn't satisfy this issue, leave a comment as to why not / what else needs done and remove the current 2.3 milestone and replace it with something else. Thanks.

**Comment by xeno6696** [comment]
This can be closed.
