### ISSUE TITLE
SecurityWrapperRequest seems to mishandle/swallow allowNull argument

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#188]
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on November 06, 2010 05:06:22_

Unit test:

assertNotNull(safeRequest.getParameter("e1", false));

Code that mishandles this test (from SecurityWrapperRequest):   

 public String getParameter(String name, boolean allowNull, int maxLength, String regexName) {
        String orig = getHttpServletRequest().getParameter(name);
        String clean = null;
        try {
            clean = ESAPI.validator().getValidInput("HTTP parameter name: " + name, orig, regexName, maxLength, allowNull);
        } catch (ValidationException e) {
            // already logged
        }
        return clean;
    }

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=178_

**Comment by jeremiahjstacey** [comment]
I am trying to trace this issue, and from what I'm seeing the allowNull argument is passed correctly through the call chain through the DefaultValidator into the StringValidationRule where it is applied in the checkEmpty method.

I do not understand what this task is identifying as an issue.  I've laid out the call stack I see below:

> SecurityWrapperRequest.getParameter(String name, boolean allowNull)
> calls
> SecurityWrapperRequest. getParameter(String name, boolean allowNull, int maxLength, String regexName)
> calls (through ESAPI Singleton reference)
> DefaultValidator.getValidInput(String context, String input, String type, int maxLength, boolean allowNull)
> calls
> DefaultValidator.getValidInput(String context, String input, String type, int maxLength, boolean allowNull, boolean canonicalize)
> Calls
> StringValidationRule.setAllowNull( boolean flag )
> And returns the result of 
> StringValidationRule.getValid( String context, String input )
>   which calls
>   StringValidationRule.checkEmpty(String context, String input, String orig)
>   Which checks for null based on the field value

In addition, I've created tests based on the original input that stubs out the HTTPServletRequest for verifying the SecureWrapperRequest null state.  It appears to operate as I'd expect.
```
    @Test
    public void testValidParam() {
        HttpServletRequest request = Mockito.mock(HttpServletRequest.class);
        //Param is vaid
        Mockito.when(request.getParameter(ArgumentMatchers.anyString())).thenReturn("notNull");
        assertNotNull(new SecurityWrapperRequest(request).getParameter("e1", false));
    }
    @Test
    public void testNullParamNotAllowed() {
        HttpServletRequest request = Mockito.mock(HttpServletRequest.class);
        //param is null, and not OK
        Mockito.when(request.getParameter(ArgumentMatchers.anyString())).thenReturn(null);
        assertNull(new SecurityWrapperRequest(request).getParameter("e1", false));
    }
    @Test
    public void testNullParamAllowed() {
        HttpServletRequest request = Mockito.mock(HttpServletRequest.class);
        // param is null, but null is OK
        Mockito.when(request.getParameter(ArgumentMatchers.anyString())).thenReturn(null);
        assertNotNull(new SecurityWrapperRequest(request).getParameter("e1", true));
    }
```
From my understanding of the issue's description, I would have expected these tests to have failed if allowNull was not being propagated.  At this time I am inclined to believe that this issue may already be resolved?

**Comment by kwwall** [comment]
@jeremiahjstacey I'm with you. I would figure that this issue was written because these tests were failing. We may have already fixed this. Have there been any **commits** since Feb 05, 2016 (the date of the last release) or maybe even before that but after Nov 06, 2010 (when Manico first reported it in Google Code) **_along the call chain_** that you documented that might explain why it is [now] working?

I'm fine closing this stating "can no longer reproduce", but I'd feel a _whole_ lot better if we could say "fixed in commit <commitHash>" or "fixed with PR# <pr#>". There have been a few PRs that I have caught that we expected to automatically close issues based on their commit messages, but those messages were slightly malformed and didn't result in auto-closing the issues and I only noticed later and manually closed them. But there's no question that I and others probably have missed some.

**Comment by kwwall** [comment]
@jeremiahjstacey new tests in PR #475 show that this problem was fixed (we are not sure exactly when), and thus I am closing this issue.
