### ISSUE TITLE
Build an encoding function specific to HTTP/Response Splitting (tactical remediation)

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#209]
_From [manico.james@gmail.com](https://code.google.com/u/manico.james@gmail.com/) on January 30, 2011 13:40:04_

I think we need a better strategy for response splitting defense.

> Right now, the only advice we give is to use the Request/Response
> wrappers, a defense that is not practical for all shops.
> 
> I think we need 2 approaches:
> 
> 1) Input Validation function that specifically strips linefeed line
> control characters after cannonicalization
> 2) Header Encoder that renders linefeed control characters innert (the
> best defense is always at the usage boundary)
> 
> Thoughts?

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=200_

**Comment by xeno6696** [comment]
Duplicate.  Fixing in #210
