### ISSUE TITLE
IntrusionException should extend EnterpriseRuntimeException

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#221]
_From [chrisisbeef](https://code.google.com/u/chrisisbeef/) on March 01, 2011 15:55:27_

To make it easier for integration into complex systems where the determination is made depending on if an uncaught exception is a security exception or normal runtime exception - all exceptions in ESAPI should either extend from EnterpriseSecurityException or EnterpriseRuntimeSecurityException

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=212_

**Comment by kwwall** [comment]
Fixed with commit cd9d412fe51bf0a2826fdbc0abfdce23faf2fffe.
Note commit comment incorrectly notes "Google Issue 212 (GitHub Issue 229)". The Google Issue # is correct, but the GitHub issue # should have been 221, not 229.
