### ISSUE TITLE
EncodeForHTML or other Encoding methods fail if there is a windows style path being encoded.

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#228]
_From [shilpi.a...@gmail.com](https://code.google.com/u/108155155500833528712/) on April 20, 2011 02:55:39_

What steps will reproduce the problem? 1. Take input :C\project\test
2. Pass this input to Encoder.encodeforhtml/encodeforhtmlattribute
3. see the output, all the "\" are removed. What is the expected output? What do you see instead? Proper encoding should happen What version of the product are you using? On what operating system? esapi-2.0_rc10 Does this issue affect only a specified browser or set of browsers? Alll Please provide any additional information below.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=219_

**Comment by xeno6696** [comment]
Cannot reproduce the problem.  If it was a problem it was fixed between 2.0RC and now.  I tried adding quotes to the input and got `C&#x3a;&#x5c;project&#x5c;test&quot;foo&quot;` which is exactly what I would expect.

**Comment by kwwall** [comment]
@xeno6696 Could be like you said that this was fixed already in an earlier 2.x release and just never closed. But I found the original description a bit obtuse so I'm not really sure. But I agree it should be closed.
