### ISSUE TITLE
exception is java.lang.NoClassDefFoundError: org.owasp.esapi.codecs.Codec

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#235]
_From [alexj...@gmail.com](https://code.google.com/u/117724374125274417382/) on June 15, 2011 05:02:44_

Hi All,

   My web project contains esapi-2.0GA.jar inside WEB-INF/lib folder. but still i am getting the below error. My application is running on websphere 6.1. Could anyone help me to resolve this issue.

exception is java.lang.NoClassDefFoundError: org.owasp.esapi.codecs.Codec

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=227_

**Comment by xeno6696** [comment]
Going to close this as this hasn't been reproducible for over 5yrs. Seems like a basic classpath issue.
