### ISSUE TITLE
how can we use esapi in java for validation,please see files attached containing java code and for errors

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#237]
_From [arjunpro...@gmail.com](https://code.google.com/u/112697525186800313795/) on June 22, 2011 02:53:32_

Hi All,
       I require one help regarding the implementation for esapi in java.when i am providing an input as 
instance.isValidInput("test", "hello@world.com", "Email", 100, false)
then it throws the following error on console--->
WARNING: SECURITY-FAILURE Anonymous@unknown:unknown -- Invalid input: context=test, type=Email( Email), input=hello@world.com
    ValidationException @ org.owasp.esapi.reference.DefaultValidator.getValidInput(null:-1)
false

On using this as Input to my source code--->getValidInput("test", "hello12@world.com", "Email", 100, false)
i get the following error as --->

Jun 22, 2011 11:34:16 AM AppNameNotSpecified IntrusionDetector
WARNING: SECURITY-FAILURE Anonymous@unknown:unknown -- Invalid input: context=test, type=Email( Email), input=hello12@world.com
    ValidationException @ org.owasp.esapi.reference.DefaultValidator.getValidInput(null:-1)
org.owasp.esapi.errors.ValidationException: test: Invalid input. Please conform to: Email with a maximum length of 100
	at org.owasp.esapi.reference.DefaultValidator.getValidInput(Unknown Source)
	at Esapi.testIsValidEmail(Esapi.java:38)
	at Esapi.main(Esapi.java:49)

can anyone please suggest on the above errors
Appreciate your help !!!

**Attachment:** [esapi.rtf errors.rtf](http://code.google.com/p/owasp-esapi-java/issues/detail?id=229)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=229_

**Comment by kwwall** [comment]
This issue is being closed because it was really a question, not a bug and the answer has already been provided in the previous comment.

**Comment by AadhiSmart** [comment]
<script>alert('hi')</script>
