### ISSUE TITLE
Patch for /trunk/src/main/java/org/owasp/esapi/reference/crypto/JavaEncryptor.java

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#254]
_From [noloa...@gmail.com](https://code.google.com/u/114558122492435650190/) on October 08, 2011 17:20:41_

Removed all those damn errant UTF-8 BOMs (EF BB BF) which made it impossible to format the source

**Attachment:** [JavaEncryptor.java.patch](http://code.google.com/p/owasp-esapi-java/issues/detail?id=247)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=247_

**Comment by kwwall** [comment]
This was already fixed by me previously, but I just forgot to close the issue. I double checked and do not detect the BOM character sequence. (Tested using "grep -iobUaP '\xef\xbb\xbf' JavaEncryptor.java" as well as using hexdump.)
