### ISSUE TITLE
Whitespace in JavaEncryptor

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#256]
_From [noloa...@gmail.com](https://code.google.com/u/114558122492435650190/) on October 15, 2011 18:08:08_

Whitespace

**Attachment:** [JavaEncryptor.java.patch](http://code.google.com/p/owasp-esapi-java/issues/detail?id=249)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=249_

**Comment by kwwall** [comment]
Confirmed that this patch is only cleanup of whitespace so this is indeed low priority. (In the mean time, set your tabsize to 4 if it bothers you.)

**Comment by jeremiahjstacey** [comment]
Closing with the merge of PR #505
