### ISSUE TITLE
I am getting validation exception while validating a paramter coming from http request

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#263]
_From [thiru...@gmail.com](https://code.google.com/u/109040330036623442590/) on December 19, 2011 02:40:25_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? i need to see the vaidated Input What version of the product are you using? On what operating system? I am using ESAPI 1.4.jar Does this issue affect only a specified browser or set of browsers? Please provide any additional information below. I am getting the below exception...please help me out on this.
Dec 19, 2011 12:57:24 PM AppNameNotSpecified IntrusionDetector
WARNING: SECURITY-FAILURE Anonymous@unknown:unknown -- Invalid input: context=Synchrozier Token, type=HTTPParameterName( HTTPParameterName), input=ea15e562efb5e786dbf5cd55443a80e1
    ValidationException @ org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:140)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=256_

**Comment by jeremiahjstacey** [comment]
@kwwall  @xeno6696   There is not enough information in this task for any work to be derived.  Though DefaultValidator is listed, the version reference is ESAPI 1.4.

I believe this task should be closed as there is not enough information.  We can always re-assess if this arises again in the active baseline.

**Comment by xeno6696** [comment]
No info to reproduce.  Killing it.
