### ISSUE TITLE
Canonicalize function for the DefaultEncoder class does not handle URLs properly

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#265]
_From [gurna...@gmail.com](https://code.google.com/u/110286511227513707989/) on January 04, 2012 09:06:16_

What steps will reproduce the problem? 1. Run the following code using the standard DefaultEncoder class: 

String paramValue = "http://localhost:8226/InfoCenter/index?page=answers&type=search&searchid=1325676169437&newsearch=y&question_box=top&quote=y";
String result = ESAPI.encoder().canonicalize(paramValue, false);
System.out.println(result);
1. The result returned is:

http://localhost:8226/InfoCenter/index?page=answers&type=search&searchid=1325676169437≠wsearch=y&question_box=top"e=y
1. Note that the &ne and &quot have been changed. What is the expected output? What do you see instead? I would expect the URL to be returned unchanged. What version of the product are you using? On what operating system? 2.0.1. Does this issue affect only a specified browser or set of browsers? Not browser specific. Please provide any additional information below. I suspect it should check for the terminating ; character before attempting HTML entity substitution.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=258_

**Comment by xeno6696** [comment]
@kwwall I think [this commit](https://github.com/ESAPI/esapi-java-legacy/commit/aafa3539002e01cc40b7d12868ab043838e62563), associated with issue #376 will fix this issue as well.  The problem was that when canonicalizing a URI, ESAPI treats the URI as a single-syntax string, ignoring URI structure.  &product=foo is legal in a URI query, and shouldn't be canonicalized.

**Comment by xeno6696** [comment]
Closing issue.  The original asker did not understand the intention of canonicalization (to get a version of the input guaranteed to be safe to perform operations upon) and an API enhancement now allows esapi to accurately canonicalize URIs.
