### ISSUE TITLE
java.lang.ClassNotFoundException: org.owasp.validator.html.PolicyException

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#267]
_From [prashmit...@gmail.com](https://code.google.com/u/113612233863243124074/) on January 29, 2012 04:53:24_

The following code is generating the above exception. 

protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        response.setContentType("text/html");
        PrintWriter out=response.getWriter();
        String mailPattern="^[A-Za-z0-9._&#37;-]+@[A-Za-z0-9.-]+\.[a-zA-Z]{2,4}$";

```
    try
    {
        DefaultValidator d=new DefaultValidator();
        boolean b=d.isValidInput("Mail_Pattern", request.getParameter( "zip" ), mailPattern, 10, false);     
                    if(b)
                    {
                       out.println("Correct e-mail");
                    }

    }
            catch(Exception e)
            {}
```

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=260_

**Comment by kwwall** [comment]
The reason for this is that in addition to including the **ESAPI** jar, for this particular use, you also need to include the **AntiSamy** jar. The `org.owasp.validator.html.PolicyException` class is part of **AntiSamy**, not **ESAPI**. As far as I can tell, there is nothing to fix here in **ESAPI**.
