### ISSUE TITLE
SecurityWrapperResponse setStatus should not always set SC_OK

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#268]
_From [pavel.ro...@gmail.com](https://code.google.com/u/113837229702366086301/) on February 11, 2012 13:39:31_

When HTTP 304 is returned back from the underlying web application, SecurityWrapperResponse transforms this code to 200. It results to corrupted caching behavior in IE, Opera,... 

maybe some kind of below logic should be better

public void setStatus(int sc) {
 if (sc != SC_MOVED_PERMANENTLY
  && sc != SC_MOVED_TEMPORARILY
  && sc != SC_CONTINUE
  && sc != SC_CREATED
  && sc != SC_NO_CONTENT
  && sc != SC_NOT_MODIFIED
  && sc != SC_PARTIAL_CONTENT
  && sc != SC_TEMPORARY_REDIRECT) {
   getHttpServletResponse().setStatus(SC_OK);
 } else {
   getHttpServletResponse().setStatus(sc);
 }
}

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=261_

**Comment by jeremiahjstacey** [comment]
SecurityWrapperResponse now only alters the return code if the property "HttpUtilities.OverwriteStatusCodes" is set to true.  See lines 509 - 516 of current baseline.

```
public void setStatus(int sc) {
    	SecurityConfiguration config = ESAPI.securityConfiguration();
    	if(config.getBooleanProp("HttpUtilities.OverwriteStatusCodes")){
    		getHttpServletResponse().setStatus(HttpServletResponse.SC_OK);
    	}else{
    		getHttpServletResponse().setStatus(sc);
    	}
        
    }
```


With current configurations I believe this task is OBE.

@

**Comment by xeno6696** [comment]
@jeremiahjstacey I agree.
