### ISSUE TITLE
Add Constructor to DefaultSecurityConfiguration to accept a properties file (1.4)

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#271]
_From [christof...@gmail.com](https://code.google.com/u/106863696289161512808/) on February 26, 2012 06:09:23_

Add constructor to DefaultSecurityConfiguration to accept 
a Properties object as a parameter and load properties from that object.  This will allow different ESAPI.properties files on the web application level.  The current method of loading ESAPI.properties is system wide, and different web apps could have different needs, thus different ESAPI.properties files may be needed.  
This is the constructor that was added.  The "logLoadedProperties" is an additional private method to log the loaded properties and can be called from either the new constructor or the existing one.

/**
- Instantiates a new configuration from a Properties object
  */
  public DefaultSecurityConfiguration(Properties p) {
  
  this.properties = p;
  this.logLoadedProperties();

}

Milestone 2.1

**Attachment:** [DefaultSecurityConfiguration.java](http://code.google.com/p/owasp-esapi-java/issues/detail?id=264)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=264_

**Comment by xeno6696** [comment]
@kwwall I don't think we need this.  At least with the current design, everything is a singleton, and this is really better served by just eliminating the singleton design.

**Comment by kwwall** [comment]
Agree. This is not the way to do this as it good unintended security
implications. E.g., a rogue 3rd party library (those don't exist, right???
;-) could possibly use this to subvert or weaken security in the
application that ESAPI is trying to protect.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.
