### ISSUE TITLE
Logger.log is is slow

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#274]
_From [bschoeni](https://code.google.com/u/bschoeni/) on April 09, 2012 15:33:35_

What steps will reproduce the problem? 1. logger = Log4JLogger.getLogger(TestESAPIValidationPatterns.class);
2. logger.warn("starting up");
3. With a debugger, step through the "warn" method's implementation

```
    // log the message
    log(level, "[" + typeInfo + getUserInfo() + " -> " + appInfo + "] " + clean, throwable);
```

String concatenation in the above code creates a StringBuilder instance for each '+' operation.  Instead, the code should use StringBuilder directly. Such as:

```
    // log the message
            StringBuilder msg = new StringBuilder(60);
            msg.append('['; msg.append(typeInfo); msg.append.(" -> "); msg.append(appinfo);
            msg.apend(']'); msg.append(clean);
    log(level, msg.toString(), throwable); What is the expected output? What do you see instead? Performance is poor for this frequently invoked method. What version of the product are you using? On what operating system? 2.0.1 on MacOS Lion Does this issue affect only a specified browser or set of browsers? No Please provide any additional information below.
```

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=267_

**Comment by xeno6696** [comment]
> Java 1.5 appears to inline the StringBuilder, so this is not a problem and should be junked.
