### ISSUE TITLE
NPE in SafeFile.doDirCheck() on empty file path, needs null check.

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#277]
_From [m.isak...@gmail.com](https://code.google.com/u/100241417243180339858/) on April 20, 2012 05:08:45_

What steps will reproduce the problem? 1. Create a SafeFile instance without path.
2. SafeFile file = new SafeFile("hello.txt")
3. NPE is thrown. What is the expected output? What do you see instead? Exptected valid SafeFile instance, got NullpointerException. What version of the product are you using? On what operating system? Trunk. Windows. Does this issue affect only a specified browser or set of browsers? No. Please provide any additional information below. @Test
    public final void safeFileShouldAcceptEmptyPath() throws ValidationException
    {
        String filename = "hello.txt";
        SafeFile file = new SafeFile(filename);

```
    assertTrue(filename.equals(file.getName()));
}
```

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=270_

**Comment by xeno6696** [comment]
The Javadoc on this issue is clear:  

>     /**
>      * Returns the pathname string of this abstract pathname's parent, or
>      * <code>null</code> if this pathname does not name a parent directory.
>      *
>      * <p> The <em>parent</em> of an abstract pathname consists of the
>      * pathname's prefix, if any, and each name in the pathname's name
>      * sequence except for the last.  If the name sequence is empty then
>      * the pathname does not name a parent directory.
>      *
>      * @return  The pathname string of the parent directory named by this
>      *          abstract pathname, or <code>null</code> if this pathname
>      *          does not name a parent
>      */
>     public String getParent() {
>         int index = path.lastIndexOf(separatorChar);
>         if (index < prefixLength) {
>             if ((prefixLength > 0) && (path.length() > prefixLength))
>                 return path.substring(0, prefixLength);
>             return null;
>         }
>         return path.substring(0, index);
>     }

I think this was designed to force callers to give full directory names to files.  Though, to me, returning `null` is a nasty, nasty antipattern.  But I've lost that battle in as many development groups as I've won it.  

Kevin, My instinct here is to just close this.  Thoughts?

**Comment by kwwall** [comment]
@xeno6696 I suppose alternately, they could have returned "." (which I believe represents the current directory in _most_ modern file systems). Or, if it really considered an error, an exception of some time should have been thrown. But if we started doing either of those, it could break existing code where people are now checking for a possible null being returned and no exception is anticipated. Our only recourse would be to switch the behavior based on some new ESAPI property and frankly, I don't think this is that important. Developers eventually will learn when the start getting NPEs. So, yes, close it with a comment that it is operating as documented along with a 'wontfix' label.

**Comment by xeno6696** [comment]
Operating as Documented.

**Comment by kwwall** [comment]
Reopening to add wontfix label. (GitHub issues didn't seem to want to allow me to add that on an already closed issue.)

**Comment by kwwall** [comment]
Duh; never mind. Need another cup of coffee. Was already marked 'wontfix'. Sorry for the confusion.
