### ISSUE TITLE
missing assertions in SafeFileTest.java

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#281]
_From [alan.cha...@gmail.com](https://code.google.com/u/113136317221772835735/) on July 11, 2012 13:55:18_

What steps will reproduce the problem? 1. No assertion; Class SafeFileTest.java; Method testEscapeCharactersInFilename
2. No assertion; Class SafeFileTest.java; Method testEscapeCharacterInDirectoryInjection What is the expected output? What do you see instead? 1. Expect to see output of unit test assertion What version of the product are you using? On what operating system? 1. ESAPI_2.0 subversion trunk Does this issue affect only a specified browser or set of browsers? 1. n/a

updated tests with assertions :

```
public void testEscapeCharactersInFilename() {
    System.out.println("testEscapeCharactersInFilenameInjection");
    File tf = testFile;
    if (tf.exists()) {
        System.out.println("File is there: " + tf);
    }

    File sf = new File(testDir, "test^.file");

    assertFalse("Injection didn't work " + sf.getAbsolutePath(),
            sf.exists());
    assertTrue("  Injection allowed " + sf.getAbsolutePath(), sf.exists());
}

public void testEscapeCharacterInDirectoryInjection() {
    System.out.println("testEscapeCharacterInDirectoryInjection");
    File sf = new File(testDir, "test\\^.^.\\file");
    assertFalse("  Injection didn't work " + sf.getAbsolutePath(),
            sf.exists());
    assertTrue("  Injection allowed " + sf.getAbsolutePath(), sf.exists());
} Please provide any additional information below.
```

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=275_

**Comment by xeno6696** [comment]
I should have tested this beforehand.  

It appears that this unit test has been in a failing state for a decade.  We allow the Windows file escape char.  

@planetlevel --do you recall why SafeString doesn't have `^` in the blacklist?
