### ISSUE TITLE
Difference between encodeForHTMLAttribute and encodeForHTML

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#282]
_From [wettstei...@gmail.com](https://code.google.com/u/108417551973747153004/) on July 18, 2012 06:31:53_

As I have seen in the source code the single difference between 
ESAPI.encoder().encodeForHTML() and ESAPI.encoder().encodeForHTMLAttribute()
is that ' ' is part of the whitelist in encodeForHTML() and therefore not encoded. 

ESAPI.encoder().encodeForHTMLAttribute() does indeed neither encode ' ' as it is part of the UNENCODED_SET (line 73 HTMLEntityCode). 

Since the two methods do apparently the same (or did I miss some point?), why is there a need to make a distinction?

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=276_

**Comment by xeno6696** [comment]
This is not a bug at all.

**Comment by kwwall** [comment]
@xeno6696 Someone was working on a ESAPI FAQ. This question gets asked quite often and perhaps should go in there, but I agree this isn't really a bug.

Also, if I'm not mistaken (and I may very well be), for cases where you doing output encoding for JavaScript event handler attributes (e.g., `onerror`, `onload`, etc.) you really should be using `Encoder.encodeForJavaScript()`, not `Encoder.encodeForHTMLAttribute()`.
