### ISSUE TITLE
nekohtml fails ESAPI.validator().getValidSafeHTML();

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#283]
_From [Christop...@googlemail.com](https://code.google.com/u/106889047842518894267/) on July 18, 2012 12:38:47_

Calling

ESAPI.validator().getValidSafeHTML();

with 

<scr<script>ipt>

returns

ipt&gt;

The problem is "nekohtml.jar". ESAPI 2.0.1 comes with nekohtml-1.9.12.jar and ESAPI 1.4 used another one which has no version in name so I am not sure which version it is but it does not matter. 1.4 works correctly but 2.0.1 returns the above descripted output. I have tried the latest version of nekohtml which is 1.9.15 and this one works fine again ("<scr<script>ipt>" => "").

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=277_

**Comment by xeno6696** [comment]
Not a problem.

`assertEquals("", instance.getValidSafeHTML("Test", "<scr<script>ipt>", 150, false));`

Works fine.
