### ISSUE TITLE
JavaLogFactory not thread safe

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#286]
_From [mike.til...@yahoo.com](https://code.google.com/u/109171368508383610253/) on July 26, 2012 10:07:44_

What steps will reproduce the problem? for (int i = 0; i < 5000; ++i) {
            new Thread(new Runnable() {
                    public void run() {
                        ESAPI.getLogger(String.valueOf(Math.random()));
                    }
                }).start();
        } What is the expected output? What do you see instead? Expect the program to finish, doesn't always finish.  Non-synchronized puts/gets to HashMap can result in an infinite loop. What version of the product are you using? On what operating system? esapi-2.0.1.jar
$ java -version
java version "1.6.0_32"
Java(TM) SE Runtime Environment (build 1.6.0_32-b05)
Java HotSpot(TM) Server VM (build 20.7-b02, mixed mode) Please provide any additional information below. Should use Collections.synchronizedMap or ConcurrentHashMap

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=280_

**Comment by kwwall** [comment]
Closed via PR #470
