### ISSUE TITLE
Patch for /trunk/src/test/java/org/owasp/esapi/reference/UserTest.java

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#288]
_From [bschoeni](https://code.google.com/u/bschoeni/) on July 27, 2012 10:01:45_

Added test case to verify Issue #281 where password is changed back to original.

**Attachment:** [UserTest.java.patch](http://code.google.com/p/owasp-esapi-java/issues/detail?id=282)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=282_

**Comment by kwwall** [comment]
Here is original proposed patch. Attaching it again because previous attachment is just patch to Google Code issue, which is going away.
[gh-288-issue282-UserTest.java.patch.txt](https://github.com/ESAPI/esapi-java-legacy/files/111590/gh-288-issue282-UserTest.java.patch.txt)

**Comment by kwwall** [comment]
Closing this issue because 1) there was already a test to see if the PREVIOUS password could be reused, and 2) our FileBasedAuthenticator.changePassword() does not maintain a general password history per se, but only ensures that the new password can't be the _previous_ one. Thus this proposed test is invalid (and in fact fails).

**Comment by kwwall** [comment]
Note that I've revised src/test/java/org/owasp/esapi/reference/UserTest.java so that the test proposed by the patch is present, but commented out along with a comment. Hopefully that will prevent someone from opening a similar issue in the future.

**Comment by kwwall** [comment]
Re-opening this. Turns out FileBasedAuthenticator did have a password history, but a bug caused it to make this test fail. Fixed #287 so will re-open this to fix it.

**Comment by kwwall** [comment]
Closed per commit f4ce180c9aab7103f9f1d6c90630267a3257025c.
