### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#294]
_From [guttikon...@gmail.com](https://code.google.com/u/112862999491106083727/) on October 15, 2012 14:03:30_

What steps will reproduce the problem? 1.Configured the Filter from the download version 1.4 2. 3. What is the expected output? What do you see instead? Expected my login page What version of the product are you using? On what operating system? ESAPI 1.4.4  on windows 2008 Does this issue affect only a specified browser or set of browsers? All browsers Please provide any additional information below.

**Attachment:** [Owsap error.txt](http://code.google.com/p/owasp-esapi-java/issues/detail?id=288)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=288_

**Comment by xeno6696** [comment]
ESAPI 1.X is End of Life.

**Comment by kwwall** [comment]
@xeno6696 That file (gh-294-issue288-Owasp-error.txt) that was part of that gzipped tarball that I recently emailed you was not much enough to go on to see if there is still an issue in ESAPI 2.x, so fair to close it. (I tried attaching it several times, but GH keeps giving me the error message "Something went really wrong, and we can't process that file. Try again." Oh well, you should already have it.)
