### ISSUE TITLE
ESAPIFilter in RI should allow login page destination to be configured

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#30]
_From [chrisisbeef](https://code.google.com/u/chrisisbeef/) on July 24, 2009 03:50:59_

Rather than force uses of the RI to have their login page be located at
/WEB-INF/login.jsp we should allow configuration of where the users should
be forwarded in the event that a forward or redirect needs to occur to log
the user in. 

We should be able to add a line to the ESAPI.properties file which allows
the user to specify where login requests should be sent.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=20_

**Comment by kwwall** [comment]
Note that PR #459 which closed this was identical to PR #460 which was rejected (as duplicate).
