### ISSUE TITLE
encodeForHTMLAttribute escapes the forward slash

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#301]
_From [julian.r...@googlemail.com](https://code.google.com/u/107651864577259151853/) on March 04, 2013 11:19:00_

Why?

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=295_

**Comment by xeno6696** [comment]
To prevent injections predicated on prematurely closing a tag.

`</span><script>alert(1);</script>`
