### ISSUE TITLE
HTMLEntityCodec#decode incorrectly decodes upper-case accented letters as their lower-case counterparts

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#302]
_From [bja...@twigkit.com](https://code.google.com/u/109723178327690826366/) on March 25, 2013 12:05:24_

What steps will reproduce the problem? 1. System.out.println(new org.owasp.esapi.codecs.HTMLEntityCodec().decode("&Aacute;")); What is the expected output? What do you see instead? I would expect the HTMLEntityCodec to correctly decode "&Aacute;" as a capital "Á". Instead, it outputs a lower-case "á". The same is true for all HTML entities whose encoding fits the "&*acute;" pattern. What version of the product are you using? On what operating system? Version 2.0.1 on MacOS X 10.8.2. Does this issue affect only a specified browser or set of browsers? Nope, this is an API issue. Please provide any additional information below. Checking out your source code from trunk (25/3/2013), it seems the problem is line 253 of HTMLEntityCodec.java (in method getNamedEntity): 

```
possible.append(Character.toLowerCase(input.next())); 
```

Here it is turning everything into lower case as it reads the input stream, thereby losing the case information for accented letters.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=296_

**Comment by sunnypav** [comment]
The issue is still happening even with the latest release of ESAPI 2.1.0.1. Please fix this.

**Comment by xeno6696** [comment]
In your debugging you've already identified the line of code.  Why not just fix it and submit a pull request?

**Comment by sunnypav** [comment]
Hi All, Please review the change & let me know the feedback for the same.

**Comment by sunnypav** [comment]
My Apologies for the duplicate pull requests please pull only the commit [005cf26](https://github.com/ESAPI/esapi-java-legacy/commit/005cf26f5aa34b702a243f7b222eb5d2db296543).

**Comment by madness-inc** [comment]
Hi  @xeno6696 ,

are there any plans to release a bugfix version (2.1.0.2) including the fix?
This is a serious bug for us, since german umlauts are also affected.

Regards
Matthias
