### ISSUE TITLE
AuthenticatedUser isCredentialsNonExpired() have todo comment, but default return false;

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#308]
_From [pengguo...@gmail.com](https://code.google.com/u/110286411528294829520/) on June 20, 2013 04:45:14_

I think this should defualt return true, so I don't override it.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=302_

**Comment by xeno6696** [comment]
This class and method is not part of our baseline.
