### ISSUE TITLE
Double checked locking on Log4JLogFactory.getInstance()

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#311]
_From [d.bo...@gmail.com](https://code.google.com/u/103603344140569081431/) on July 31, 2013 13:15:30_

There is a double checked locking error on Log4JLogFactory.getInstance().
This issue could result in returning a partially constructed object.

For more details see: http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html You could synchronize the whole method or to avoid the overhead of synchronization, you could directly instantiate the object on the declaration line.

like:

private static final LogFactory singletonInstance = new Log4JLogFactory();

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=305_

**Comment by kwwall** [comment]
This should be okay since singletonInstance in the Log4JLogFactory class is declared with the 'volatile' modifier. Closing the issue.
