### ISSUE TITLE
ValidatorTest.testIsValidDate fails if default locale is not US

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#315]
_From [Dietrich.Frank@gmail.com](https://code.google.com/u/Dietrich.Frank@gmail.com/) on November 06, 2013 17:26:51_

What steps will reproduce the problem? 1. export LANG=de_DE.UTF-8
2. mvn clean -Dtest=ValidatorTest#testIsValidDate test

What is the expected output? 
- the test should pass

What do you see instead?
- Failed tests:   testIsValidDate(org.owasp.esapi.reference.ValidatorTest)

Attached a patch to use SimpleDateFormat with Locale.US instead of using the environment default Locale.

**Attachment:** [testIsValidDate.patch](http://code.google.com/p/owasp-esapi-java/issues/detail?id=310)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=310_

**Comment by kwwall** [comment]
Also fixed with commit 300bdf3a4c0202ed8507f0c8d8a57dc6dc41a921. (See GitHub issue #347.)
