### ISSUE TITLE
Incorrect Equality test on floating point values

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#318]
_From [eamonn.w...@gmail.com](https://code.google.com/u/104114803397285871233/) on November 26, 2013 14:23:09_

I have V2.1 sources.

2 places in RuleUtil.java have an invalid floating point comparison logic.

The corrected block(for both cases) is:

                                                                                if ( Double.compare(Double.parseDouble(s), ((Double)o).doubleValue()) ==  0 ) {

                                                                                                return true;

                                                                                }

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=313_

**Comment by xeno6696** [comment]
Converted this into a patch for your convenience.  @kwwall recommend closing.  

[issue318.txt](https://github.com/ESAPI/esapi-java-legacy/files/76074/issue318.txt)
