### ISSUE TITLE
Resource leak: FileInputStream is not closed on method exit

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#319]
_From [eamonn.w...@gmail.com](https://code.google.com/u/104114803397285871233/) on November 26, 2013 14:48:44_

I have V2.1 sources.

2 places in ESAPIWebApplicationFirewallFilter.java do not close file streams.

The corrected 2 methods are:

public void setConfiguration( String policyFilePath, String webRootDir ) throws FileNotFoundException {

                               

                                FileInputStream inputStream = null;

                                try {

                                                inputStream = new FileInputStream(new File(policyFilePath));

                                                appGuardConfig = ConfigurationParser.readConfigurationFile(inputStream, webRootDir);

                                                lastConfigReadTime = System.currentTimeMillis();

                                                configurationFilename = policyFilePath;

                                } catch (ConfigurationException e ) {

            // TODO: It would be ideal if this method through the ConfigurationException rather than catching it and

            // writing the error to the console.

                                                e.printStackTrace();

                                } finally {

                                                if (inputStream != null) {

                                                                try {

                                                                                inputStream.close();

                                                                } catch (IOException e) {

                                                                                e.printStackTrace();

                                                                }

                                                }

                                }

                }

/* and the block ... */

  FileInputStream inputStream = null;

                                try {

 

                                                String webRootDir = fc.getServletContext().getRealPath("/");

                                                inputStream = new FileInputStream(configurationFilename);

                                                appGuardConfig = ConfigurationParser.readConfigurationFile(inputStream, webRootDir);

 

                                                DOMConfigurator.configure(realLogSettingsFilename);

 

                                                lastConfigReadTime = System.currentTimeMillis();

                                               

                                } catch (FileNotFoundException e) {

                                                throw new ServletException(e);

                                } catch (ConfigurationException e) {

                                                throw new ServletException(e);

                                } finally {

                                                if (inputStream != null) {

                                                                try {

                                                                                inputStream.close();

                                                                } catch (IOException e) {

                                                                                e.printStackTrace();

                                                                }

                                                }

                                }

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=314_

**Comment by xeno6696** [comment]
Converted this to a patch for easy application.  @kwwall , recommend closing.  

[issue319.txt](https://github.com/ESAPI/esapi-java-legacy/files/76070/issue319.txt)

**Comment by kwwall** [comment]
Fixed with commit dffaddbb59946fb4ba46d5fb97830af277b408d7.
