### ISSUE TITLE
Unsynchronized get method, synchronized set method

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#321]
_From [eamonn.w...@gmail.com](https://code.google.com/u/104114803397285871233/) on November 26, 2013 14:57:37_

I have V2.1 sources.

The class ReferenceEncryptedProperties.java has a synchronized setter and one of the two getters is also synchronized.  The second setter should also be synchronized for well behaved synchronization.

The corrected method signature follows:

public synchronized String getProperty(String key, String defaultValue) throws EncryptionRuntimeException {

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=316_

**Comment by xeno6696** [comment]
@kwwall Looks like a straightforward bugfix here.  Apply and recommend closing?

**Comment by kwwall** [comment]
Will be fixed with next push I do to GitHub.
