### ISSUE TITLE
RequestRateThrottleFilter may not work as expected with hits=1 or hits=2

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#322]
_From [eric.cit...@gmail.com](https://code.google.com/u/102979787554200428370/) on January 01, 2014 13:11:08_

As stated in my comment ( https://code.google.com/p/owasp-esapi-java/source/browse/trunk/src/main/java/org/owasp/esapi/filters/RequestRateThrottleFilter.java?spec=svn1940&r=1940#86 ), RequestRateThrottleFilter may not work as expected when configured with hits=1 or hits=2.

I would like to suggest another implementation (see the attached patch).

Thanks,
Eric.

**Attachment:** [RequestRateThrottleFilter.patch](http://code.google.com/p/owasp-esapi-java/issues/detail?id=317)

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=317_

**Comment by xeno6696** [comment]
@kwwall Are we taking this patch as-is?  What would you like me to do here?

**Comment by xeno6696** [comment]
Actually, another small bug here.  In the servlet init:

```
    //Note that we set hardcoded defaults in the class:
    private int hits = 5;

    private int period = 10;
    // stuff
    // Here we should be checking for null, so that the defaults we already specified are used 
    // instead of trying to possibly parse nulls.  

    public void init(FilterConfig filterConfig)
    {
        hits = Integer.parseInt(filterConfig.getInitParameter(HITS));
        period = Integer.parseInt(filterConfig.getInitParameter(PERIOD));
    }
```
I've attached a patch to handle the null check.  
[RequestRateThrottle.txt](https://github.com/ESAPI/esapi-java-legacy/files/74019/RequestRateThrottle.txt)

**Comment by xeno6696** [comment]
One more question about the original code here @kwwall , I noticed that we're calling `intern()` on the session ID that we get.  Is this wise?  This usually signifies a memory leak.  

```
   public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException
    {
        HttpServletRequest httpRequest = (HttpServletRequest) request;
        HttpSession session = httpRequest.getSession(true);
        
        synchronized( session.getId().intern() ) {
	        Stack<Date> times = ESAPI.httpUtilities().getSessionAttribute("times");
```

**Comment by kwwall** [comment]
@xeno6696 Not sure why the call to String.intern() here. However, it's being used at as a synchronization lock, so maybe it's being used as a fine-grained lock on a specific string in the String pool. I don't think it's going to cause any memory leak issues though.

@planetlevel - Jeff, do you know what String.intern() is used here?

**Comment by xeno6696** [comment]
`String.intern()` forces the string into permanently non-garbage collected memory.  For session ids on a server that handles thousands of requests,  and randomly generated strings small chance this won't cause a memory leak.  

The only time you want to use that method is in embedded systems with limited processor speed, and even then, you need to make sure that *all* string comparisons use it.

**Comment by kwwall** [comment]
@xeno6696 @planetlevel Would be nice of Oracle would document that nasty side effect in the Javadoc for String.intern() then.  Waiting for Jeff's to reply. (Sent him separate email and CC'd you, Matt.) It seems like
```
synchronized( session.getId() ) {
```
would have worked fine here, but I want to make sure I'm not missing something more subtle in terms of lock contention or whatever.

**Comment by xeno6696** [comment]
Did some research, this bug appears to have been resolved:  http://bugs.java.com/view_bug.do?bug_id=6962931
