### ISSUE TITLE
setHeader blocks legitimate headers due to header name size limit being too low

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#330]
_From [jac...@gmail.com](https://code.google.com/u/107079895399630993312/) on April 13, 2014 01:59:55_

What steps will reproduce the problem? 1. Write a Servlet that uses DefaultHTTPUtilities.getInstance().setHeader(...) to set headers to the response
2. Attempt to write a header with a name longer than 20 characters, such as "Strict-Transport-Security" or "Access-Control-Allow-Origin" What is the expected output? What do you see instead? These headers are standard and not unsafe, so I expect them to pass validation, but they are blocked by what seems to be an arbitrary (and quite low) character limit of 20 characters. What version of the product are you using? On what operating system? 2.1.0 (loaded using maven as dependency of project) because it appears to be the latest stable version as of 4/13/2014.
I am using Tomcat 7.0.41 on Linux, but in this case I think that's irrelevant. Does this issue affect only a specified browser or set of browsers? No. Please provide any additional information below. How can I modify this character limit without forking / modifying the source code? It appears to be hard-coded. Could this at least be increased to a higher default like 32 or 40?

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=326_

**Comment by xeno6696** [comment]
It is hardcoded.

```
    public void setHeader(HttpServletResponse response, String name, String value) {
        try {
            String strippedName = StringUtilities.replaceLinearWhiteSpace(name);
            String strippedValue = StringUtilities.replaceLinearWhiteSpace(value);
            String safeName = ESAPI.validator().getValidInput("setHeader", strippedName, "HTTPHeaderName", 20, false);
            String safeValue = ESAPI.validator().getValidInput("setHeader", strippedValue, "HTTPHeaderValue", 500, false);
            response.setHeader(safeName, safeValue);
        } catch (ValidationException e) {
            logger.warning(Logger.SECURITY_FAILURE, "Attempt to set invalid header denied", e);
        }
    }
```

I don't have enough history to know 1.)  Why this was hardcoded, 2.)  Why this wasn't set up as a configurable property.

**Comment by kwwall** [comment]
@xeno6696 I suspect that it is hard-coded because we already have too many ESAPI properties and until a recent commit, adding new properties was a major PITA. (It is somewhat less painful to add them now, but I counted 94 properties in the test ESAPI.properties file, and until they all are more thoroughly documented, I am reluctant to add a new one, although that's probably the best way to control this short of changing the method signature. (Oh to have C++'s or C#'s default method parameters.) I could not find any specified limit in RFC 2616. Tomcat defaults to 8k, but I think that's the header name and header value combined.

Anyhow, for the meantime, I'm going to increase the size of allowable HTTP headers from 20 to 50 characters.

**Comment by xeno6696** [comment]
Just remember that elsewhere in the same class we use a default of 200.  I'm just saying... Consistency is important.

**Comment by kwwall** [comment]
Latest commits now using 50 for length of header _names_ (but can go up to
150). See the new regex for Validator.HTTPHeaderName in the latest
ESAPI.properties files.

Also, related, the HTTP header *value* can be up to 200.

I had to change several places to get this all to work, but I think I got
it right. OTOH, it was *very* late when I pushed this commit to GitHub, so
please do let me know if I missed anything.

-kevin
Sent from my Droid; please excuse typos.
