### ISSUE TITLE
-Log4JLogger.java doesn't output correct file & line number-Similar issue as reported in Issue 268

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#336]
_From [thiruthi...@gmail.com](https://code.google.com/u/118255500731866402402/) on July 10, 2014 22:57:35_

I am mainly using ESAPI(ESAPI 2.1.0) for Logging with Log4j integration

I am using JDK 1.5 & log4j 1.2.12 and running application on websphere 6.1.

The Source file name and line Number is always logged as Log4JLogger.java:449. Tried to change the pattern in log4j.properties and does not have resolve the issue.

Please share the details if anyone already experienced this issue. not sure whether it is a jar version compatibility issues.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=333_

**Comment by xeno6696** [comment]
There isn't enough information in this issue to attempt troubleshooting.  Please provide a sample project that reproduces the issue, preferably a maven project that can easily be imported into eclipse.

**Comment by kwwall** [comment]
Insufficient information is provided to reproduce the issue and it works in most general cases so this much be some edge case where it is failing.

I am closing this issue. If someone wishes to resubmit in in a manner that allows us to reproduce the issue, then please open a new issue. Thanks.
-kevin

**Comment by kwwall** [comment]
Also, note that GitHub Issue 278 (Google Issue 268) has been fixed, so this may fix the original problem as well.
