### ISSUE TITLE
DefaultHttpUtilities.getParameter gets headers, not parameters

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#34]
_From [cyounk...@gmail.com](https://code.google.com/u/110242786105136439221/) on July 28, 2009 16:55:12_

Line 608 of DefaultHttpUtilities:
String value = request.getHeader(name);

So it gets a header, just like getHeader, instead of the parameter. I think
getParameter was what was intended: http://java.sun.com/j2ee/sdk_1.3/techdocs/api/javax/servlet/ServletRequest.html#getParameter(java.lang.String) But that spec is decidedly ambiguous - Does the param come from POST or
GET? I'm not sure if we really want to use that... What version of the product are you using? On what operating system? SVN revision 574 .

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=24_

**Comment by Vaibs** [comment]
Its a pain when I have a huge JSON in POST  and wants to validate using the ESAPI. Do we have anything concrete to validate a heavy json using ESAPI ?
