### ISSUE TITLE
ESAPI configuration files not included in dist.

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#341]
_From [j.p.cran...@gmail.com](https://code.google.com/u/101461136724434044265/) on October 20, 2014 07:24:46_

> What steps will reproduce the problem?
1. Download esapi-2.1.0-dist.zip: https://code.google.com/p/owasp-esapi-java/downloads/detail?name=esapi-2.1.0-dist.zip 2. Look inside, in the folder 'configuration'

> What is the expected output?
I expect a sub folder ".esapi", just like the wiki says: https://code.google.com/p/owasp-esapi-java/wiki/esapi4java_v2_Installing_ESAPI_for_Java > What do you see instead?
Amzingly, there's nothing there!

> What version of the product are you using?
Latest release: 2.1.0.

> Please provide any additional information below.
I believe this was introduced when the '.esapi' folder was renamed to 'esapi' in SVN: https://code.google.com/p/owasp-esapi-java/source/detail?r=1670 In this change, the assembly descriptor 'src/main/assembly/dist.xml' was not changed to include the renamed folder.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=338_

**Comment by demkada** [comment]
This issue is no longer about the latest version which is available here: https://github.com/ESAPI/esapi-java-legacy/releases

**Comment by xeno6696** [comment]
Cake.  Attached a patch.  
[341.txt](https://github.com/ESAPI/esapi-java-legacy/files/71753/341.txt)
