### ISSUE TITLE
JUnit test failure in ValidatorTest.testGetValidSafeHTML()

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#344]
When all the JUnit tests are run against the latest official ESAPI release, there is following failure:

> Failed tests:   testGetValidSafeHTML(org.owasp.esapi.reference.ValidatorTest): expected:<Test.> but was:<Test. alert(document.cookie)>
> 
> Tests run: 540, Failures: 1, Errors: 0, Skipped: 0

The error seems to be coming from src/test/java/org/owasp/esapi/reference/ValidatorTest.java, in testGetValidSafeHTML(). Haven't looked at it any deeper than this.

**Comment by demkada** [comment]
This bug has already been fixed.
Waiting for a pull request validation from

**Comment by xeno6696** [comment]
I think this can be closed, @kwwall

**Comment by kwwall** [comment]
Agree, but I am having some git merge conflicts that need resolved.

Someone just gave me some steps to try today. I will try to give
those steps a shot Tues or Wed.

-kevin

On Mon, Dec 21, 2015 at 4:05 PM, xeno6696 <notifications@github.com> wrote:

> I think this can be closed, @kwwall <https://github.com/kwwall>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESAPI/esapi-java-legacy/issues/344#issuecomment-166420590>
> .
>



-- 
Blog: http://off-the-wall-security.blogspot.com/
NSA: All your crypto bit are belong to us.

**Comment by kwwall** [comment]
Fixed with commit 89815df046baa67b0f9d3deef22f2c06933dc653.
