### ISSUE TITLE
getHeader length limit error

### ISSUE THREAD

**Issue by xpressSong** [ESAPI/esapi-java-legacy#351]
ESAPI.validator().getValidInput("HTTP header value (" + name + "): " + value, value, "HTTPHeaderValue", 150, true);

if found length limit 150 in SecurityWrapperRequest.java getHeader method,but it throws a exception when is use it to get user-agent for ie8, it's 162 chractors,

**Comment by xeno6696** [comment]
Other calls in the same method are using a default of 200.  

1diff --git a/src/main/java/org/owasp/esapi/filters/SecurityWrapperRequest.java b/src/main/java/org/owasp/esapi/filters/SecurityWrapperRequest.java
index 2777e42..2be47f2 100644
--- a/src/main/java/org/owasp/esapi/filters/SecurityWrapperRequest.java
+++ b/src/main/java/org/owasp/esapi/filters/SecurityWrapperRequest.java
@@ -192,7 +192,7 @@
         String value = getHttpServletRequest().getHeader(name);
         String clean = "";
         try {
-            clean = ESAPI.validator().getValidInput("HTTP header value: " + value, value, "HTTPHeaderValue", 150, true);
+            clean = ESAPI.validator().getValidInput("HTTP header value: " + value, value, "HTTPHeaderValue", 200, true);
         } catch (ValidationException e) {
             // already logged
         }
`

**Comment by xpressSong** [comment]
thanks for your great work
