### ISSUE TITLE
Make end-of-line terminators consistent for .java, .xml, and other ESAPI source files.

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#356]
Previously we have had pull requests submitted by people working on Windows machines where the default EOL characters are CRLF. When editing a file that was previously committed from *nix or MacOS the EOL characater would be a LF character. Editing on Windows sometimes changed all the lines to Window's CRLF or in a few cases, conditions where there was a mixture of CRLF and LF end-of-line terminators. Dealing with the latter especially is a royal PITA when using vim because it shows the CR characters as it is not sure what the EOL character should be in that case. This has also lead to cases where the pull requests unnecessarily caused there to appear differences that were not really important.

The purpose of this GitHub issue is mostly a tracking issue for release notes. A few of us decided that we will use LF for EOL characters on most of the ESAPI source files. (Exceptions are dealt with in the .gitattributes file.)

**Comment by kwwall** [comment]
Closing this issue as I think I've fixed all of these issues, one-by-one, with the last series of commits. Will reopen if not. Curse you Bill Gates and Paul Allen! Why did you have to have DOS and Windows use an extra character for the end-of-line terminator? Sigh.

**Comment by xeno6696** [comment]
PITA label... FOR THE WIN!

**Comment by kwwall** [comment]
:) Of it was, trust me.

If you like that, check out my new test code in
EncoderTest.testBase64decodToObject(). Against my better judgement, I caved
and added an explanatory hint because I was afraid that most wouldn't pick
up on the Drapper hacker connection even if they did catch the pun.
-kevin

On Tue, Jan 19, 2016 at 10:36 PM, Matt Seil <notifications@github.com>
wrote:

> PITA label... FOR THE WIN!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ESAPI/esapi-java-legacy/issues/356#issuecomment-173075358>
> .
>



-- 
Blog: http://off-the-wall-security.blogspot.com/
NSA: All your crypto bit are belong to us.
