### ISSUE TITLE
AuthenticatorTest.setCurrentUser() periodically fails.

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#360]
There is an apparent race condition either in this test itself or in the FileBasedAuthenticator class that is used (indirectly) in the test. It seems to be failing about 20-30% of the time on my laptop (a dual core i5); YMMV.

@jeremiahjstacey and @xeno6696 are have been looking into this. Since no one is likely using FileBasedAuthenticator in any enterprise production scenario (if they are, they really need to re-evaluate that decision!), I am going to go ahead and release ESAPI 2.1.0.1 even if we do not have a code fix for this issue by the time of the release. If not, I will mention it in the release notes.

**Comment by xeno6696** [comment]
Wow @jeremiahjstacey it was TWO years ago!!!!

**Comment by kwwall** [comment]
I just recently got a failed test case that seems related to this:


testGetCurrentUser(org.owasp.esapi.reference.AuthenticatorTest)  Time elapsed: 0.156 sec  <<< ERROR!
org.owasp.esapi.errors.AuthenticationAccountsException: Account creation failed
        at org.owasp.esapi.reference.FileBasedAuthenticator.createUser(FileBasedAuthenticator.java:240)
        at org.owasp.esapi.reference.AuthenticatorTest$1.run(AuthenticatorTest.java:221)
        at java.lang.Thread.run(Thread.java:745)

**Comment by kwwall** [comment]
Changing this to a low priority because no one in the right minds should be using the toy implementation of `FileBasedAuthenticator`.

**Comment by kwwall** [comment]
**Note**: I set the label 'help wanted' on this issue not because this is a good first issue, but rather because we could use some assistance on it as we cannot reproduce this on demand and thus are unable to debug it.

**Comment by kwwall** [comment]
Closed via PR #467
