### ISSUE TITLE
Update pom.xml to use latest Maven plugins

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#361]
Running mvn gives the following. Let's see if we can get these cleaned up.

[INFO] The following plugin updates are available:
[INFO]   maven-assembly-plugin .................................... 2.4 -> 2.6
[INFO]   maven-changelog-plugin ................................... 2.2 -> 2.3
[INFO]   maven-compiler-plugin .................................... 3.1 -> 3.3
[INFO]   maven-eclipse-plugin .................................... 2.9 -> 2.10
[INFO]   maven-enforcer-plugin ................................ 1.3.1 -> 1.4.1
[INFO]   maven-gpg-plugin ......................................... 1.5 -> 1.6
[INFO]   maven-jar-plugin ......................................... 2.4 -> 2.6
[INFO]   maven-javadoc-plugin ................................ 2.9.1 -> 2.10.3
[INFO]   maven-pmd-plugin ......................................... 3.1 -> 3.6
[INFO]   maven-release-plugin ................................... 2.5 -> 2.5.3
[INFO]   maven-surefire-report-plugin ........................... 2.17 -> 2.19
[INFO]   org.codehaus.mojo:cobertura-maven-plugin ................. 2.6 -> 2.7
[INFO]   org.codehaus.mojo:findbugs-maven-plugin .............. 2.5.3 -> 2.5.5
[INFO]   org.codehaus.mojo:versions-maven-plugin .................. 2.1 -> 2.2
[INFO]   org.owasp:dependency-check-maven .................... 1.2.11 -> 1.3.3
[INFO] 
[WARNING] The following plugins do not have their version specified:
[WARNING]   maven-clean-plugin ........................ (from super-pom) 3.0.0
[WARNING]   maven-deploy-plugin ....................... (from super-pom) 2.8.2
[WARNING]   maven-install-plugin ...................... (from super-pom) 2.5.2
[WARNING]   maven-resources-plugin ...................... (from super-pom) 2.7
[WARNING]   maven-site-plugin ........................... (from super-pom) 3.4
[WARNING]   maven-surefire-plugin ...................... (from super-pom) 2.19

**Comment by artfullyContrived** [comment]
I can take this.

It appears that the mvn command to run for this is

`mvn versions:display-plugin-updates`

I intend to update the plugin versions and provide the missing versions.
