### ISSUE TITLE
Synchronize instance with GitHub issues

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#371]
Atlassian has allowed us to create and use JIRA for free. It is at
https://owasp-esapi.atlassian.net/browse/ESAPILEG
It needs to be synchronized with the GitHub issues for esapi-java-legacy so that if someone creates a GitHub issue, a JIRA ticket is automatically created and if someone creates a JIRA ticket, a GitHub ticket is created. Any volunteers?

**Comment by xeno6696** [comment]
Kevin.  It appears we have a JIRA gremlin...

[This issue is completed. ](https://owasp-esapi.atlassian.net/projects/ESAPILEG/issues/ESAPILEG-309?filter=allopenissues) 

Great job!

**Comment by kwwall** [comment]
Oh yeah, I forgot about that. I think @chrisisbeef set it up.

Just ignore it unless you can figure out how to sync from JIRA to GitJib
issues. I don't have the energy even though JIRA is a better bug tracker.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.
