### ISSUE TITLE
Create File Validator that checks Magic Bytes as Opposed to Extensions

### ISSUE THREAD

**Issue by xeno6696** [ESAPI/esapi-java-legacy#373]
This Might make more sense as its own little mini-module, but we can discuss it here.  Apache [Tika](https://tika.apache.org/) is a library that can be used to parse and inspect file headers to determine actual file types to mitigate the issue of say, renaming `netcat.exe` to `imsafe.docx` for the purposes of getting a file into a file store/system/whatever.  

The current esapi file validator literally just looks at a list of extensions in a properties file, and checks that the extensions are allowed.  This won't catch the case where someone uploaded a file and renamed the extension, which we could catch and throw an intrusion exception.  

Tika is a heavy, heavy library however, and would bring in a slew of parsing dependencies.  (it is painful in an airgap.)  

So should we do it here, or should OWASP create a depedent downstream project that relies on ESAPI interfaces, in order to manage the dependencies?  @kwwall @planetlevel do you have any preferences?

**Comment by kwwall** [comment]
Take a look at the new OWASP project
https://github.com/righettod/document-upload-protection instead. I think it
is a lot lighter weight and does most of what we'd like it to do.

-kevin

**Comment by kwwall** [comment]
Unless of course 'document-upload-protection', in turn, is using Apache
Tika. I've not looked at the implementation details yet, but the
functionality sounds like what we need.

-kevin

**Comment by xeno6696** [comment]
That one's a little bit different but shows promise... that library is designed to check specified files for code.  It will block outright files with any macros.  That'll block quite a few use-cases, though that's clearly a safe default.  It should probably be extended to make it configurable to create whitelists of acceptable document APIs.  (ie, disallow macros that call out to external sources, etc.)

At any rate, it doesn't solve the use-case I have in mind: detect when an advertised extension doesn't match what the file actually _is_.

**Comment by xeno6696** [comment]
It's also basically an alpha-stage project.  First commit was 3 months ago.

**Comment by kwwall** [comment]
Yeah, I knew that is was alpha. How many additional dependencies would
using Tika pull in?  ESAPI already has something like 29.

-kevin

**Comment by xeno6696** [comment]
I'm not sure of the total number offhand, but my Intern took approximately two days to track and download them all into our private nexus server.  Declared dependencies are big, at least 30, transitive dependencies are ridiculous.

**Comment by xeno6696** [comment]
A good rule of thumb:  For every document type detected, there's a custom parser included, each with multiple dependencies.  

[Here's the document types.](https://tika.apache.org/1.12/formats.html)

**Comment by kwwall** [comment]
Hmm, that would pretty much make it a show-stopper for all bit large
projects that already include most of those transitive dependencies.

Maybe we should consider adding a new 'esapi-contrib' GitHub repo similar
to what we had at Google Code. (I don't think that was ever migrated. Do
you know @chrisisbeef?)

-kevin

**Comment by kwwall** [comment]
Really no other completely safe way to do it though. Maybe this is
something to defer to ESAPI 3, when hopefully we've figured a way out of
the dependency mess we find ourselves in?

Also, I would suggest shifting this discussion to ESAPI-USER mailing list
to see if we can get feedback from users of how many additional
dependencies they would tolerate for this type of functionality. Those
people are unlikely to weigh in on those things here.

-kevin

**Comment by augustd** [comment]
I like the idea of making it an optional sub-project (in fact all of ESAPI should be optional sub-projects). 

BTW: If you want a library that just does all of ESAPI's file validations, with no dependencies, check out OWASP Java File I/O: https://github.com/augustd/owasp-java-fileio

**Comment by kwwall** [comment]
@augustd I think what @xeno6696 was looking for was something that would actually validate file CONTENT or at least, at a minimum, the file's magic #. owasp-java-fileio doesn't appear to do that.

However, Matt, I think August has a point. If you really want to add this functionality, you might be better off forking owasp-java-fileio and them making a pull request to them instead of adding it to ESAPI. Sure, it may had some dependencies, but in a project that has none, that's probably acceptable.

**Comment by xeno6696** [comment]
I'll do that, and close this issue.
