### ISSUE TITLE
SecurityWrapperResponse is overwriting http status codes that conflicts with RESTful Web Service protocols

### ISSUE THREAD

**Issue by xeno6696** [ESAPI/esapi-java-legacy#383]
See this [SO Post](http://stackoverflow.com/questions/41851159/esapi-securitywrapper-and-rest-interfaces?noredirect=1#comment72622808_41851159) for reference.

We need to modify the library so that it allows users to override our settings so applications can be compliant with RESTful contracts.

**Comment by xeno6696** [comment]
@kwwall I don't think this issue needs to be closed before the point-release.  If you can review the rest of the issues I've got assigned to me, I think all my part is done for now.

**Comment by kwwall** [comment]
Will send you a separate email on those issues. (I count 4 of them still marked 'opened'.)

**Comment by xeno6696** [comment]
This commit exposes a simple boolean property `HttpUtilities.OverwriteStatusCodes` that allows an implementor to turn off the error code rewriting ability of the class.  

The class should be rewritten to be more unit-testable than it is... I haven't done anything wrong in regards to what's been done before, but I since a major refactor is already in planning, I didn't want to start that effort right here.
