### ISSUE TITLE
Method logSpecial in DefaultSecurityConfiguration is private and cannot be overriden by subclasses

### ISSUE THREAD

**Issue by matthiaslarisch** [ESAPI/esapi-java-legacy#385]
To be able to change the behaviour of the method logSpecial() in DefaultSecurityConfiguration to e.g. put the output to an own Logger, the methods needs to be protected instead of private.

**Comment by kwwall** [comment]
Closed via PR #451

**Comment by kwwall** [comment]
Should have mentioned this in the GitHub issue instead of only in the PR #451...
This was not done in the way the way that was requested, but output from `logSpecial()` can now be suppressed by setting the `System` property **org.owasp.esapi.logSpecial.discard** to `true`.
