### ISSUE TITLE
Provide an option for the encodeForLDAP method to not encode wildcard characters

### ISSUE THREAD

**Issue by JoelRabinovitch** [ESAPI/esapi-java-legacy#389]
Hi,

Currently the encodeForLDAP method in the DefaultEncoder class encodes wildcard (*) characters.

While this is useful when trying to do a direct match on a value in an LDAP directory, you cannot use the method to find values in an LDAP directory using wildcards, while at the same time, escaping other potentially dangerous characters.  The scenario would be used when developing an LDAP query tool.

To resolve this issue, the encodeForLDAP method needs to be changed from:

// From:
    
    /**
     * {@inheritDoc}
     */
    public String encodeForLDAP(String input) {
        if( input == null ) {
            return null;    
        }
        // TODO: replace with LDAP codec
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);
            switch (c) {
            case '\\':
                sb.append("\\5c");
                break;
            case '*':
                sb.append("\\2a");
                break;
            case '(':
                sb.append("\\28");
                break;
            case ')':
                sb.append("\\29");
                break;
            case '\0':
                sb.append("\\00");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }

to:

 // Start JavaDoc for Encoder Interface.
    
    /**
     * Encode data for use in LDAP queries. Wildcard (*) characters will be escaped.
     *
     * @param input the text to encode for LDAP
     *
     * @return input encoded for use in LDAP
     */
    
    // End JavaDoc for Encoder Interface.
    

    /**
     * {@inheritDoc}
     */
    public String encodeForLDAP(String input) {
        return encodeForLDAP(input, true);
    }

    // Start JavaDoc for Encoder Interface.
    
    /**
     * Encode data for use in LDAP queries. You have the option to escape wildcard (*) characters.
     *
     * @param input the text to encode for LDAP
     * @param escapeWildcards whether or not wildcard (*) characters will be escaped.
     *
     * @return input encoded for use in LDAP
     */
    
    // End JavaDoc for Encoder Interface.

    /**
     * {@inheritDoc}
     */
    public String encodeForLDAP(String input, boolean escapeWildcards) {
        if (input == null) {
            return null;
        }
        // TODO: replace with LDAP codec
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);

            if (c == '\\') {
                sb.append("\\5c");
            }
            else if ((c == '*') && escapeWildcards) {
                sb.append("\\2a");
            }
            else if (c == '(') {
                sb.append("\\28");
            }
            else if (c == ')') {
                sb.append("\\29");
            }
            else if (c == '\0') {
                sb.append("\\00");
            }
            else {
                sb.append(c);
            }
        }

        return sb.toString();
    }

Using the original method will preserve the original behaviour, If you call the overloaded method (i.e. encodeForLDAP(string, Boolean), the developer can be control whether or wildcards should be escaped.

I am also including the original version, an updated class with the change, as well as a "diff" between the original and updated version.

[DefaultEncoderOriginal.java.txt](https://github.com/ESAPI/esapi-java-legacy/files/984413/DefaultEncoderOriginal.java.txt)
[DefaultEncoder.java.txt](https://github.com/ESAPI/esapi-java-legacy/files/984414/DefaultEncoder.java.txt)
[DefaultEncoder.java.diff.txt](https://github.com/ESAPI/esapi-java-legacy/files/984415/DefaultEncoder.java.diff.txt)

If you have any questions, or need more information.

Thanks,

Joel

**Comment by kwwall** [comment]
Joel,
Any chance you you create a GitHub issue for this and attach it as a PR?

Thanks,
-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by JoelRabinovitch** [comment]
Hi,

I have created the pull request for you, as requested.

Let me know if it's OK.

Thanks,

Joel

**Comment by JoelRabinovitch** [comment]
Hi,

I have created the pull request for you, as requested.

Let me know if it's OK.

Thanks,

Joel

**Comment by kwwall** [comment]
Our local OWASP group is having a code jam for ESAPI next Thursday (5/25).
I plan to have some new to ESAPI review the PRs at that time.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by kwwall** [comment]
@JoelRabinovitch I'm going to merge your PR, but just wanted to let you know (a bit late, sorry for that) that my preference would have been to leave the encoder as a 'switch' statement rather than as series of if-else if-else if-...-else clauses as I think that structure is a bit easier for the JIT to optimize. NBD though as I don't think encodeForLDAP() gets called all that often.

**Comment by JoelRabinovitch** [comment]
Hi,

Thanks for merging it in.

If we ever want to adjust this to use a case statement as you suggested, here is a way to do it:

        for (int i = 0; i < input.length(); i++) {
            char c = input.charAt(i);

            switch (c) {
                case '\\':
                    sb.append("\\5c");
                    break;
                case '*': 
                    if (encodeWildcards) {
                        sb.append("\\2a"); 
                    }
                    else {
                        sb.append(c);
                    }
                    
                    break;
                case '(':
                    sb.append("\\28");
                    break;
                case ')':
                    sb.append("\\29");
                    break;
                case '\0':
                    sb.append("\\00");
                    break;
                default:
                    sb.append(c);
            }
        }

If you want me to make a pull request to do this, let me know, and I will adjust the code accordingly.

Thanks,

Joel
