### ISSUE TITLE
Update Resource path search to maintain legacy behavior in DefaultSecurityConfiguration.java

### ISSUE THREAD

**Issue by xeno6696** [ESAPI/esapi-java-legacy#397]
See line 655-658.  This changed in 2.1.0.1 and we just need to make sure we search the original path too.

**Comment by kwwall** [comment]
@xeno6696 I guess the only question is whether we should add this old "resources" path BEFORE or AFTER "src/main/resources/". Do you have any thoughts on that?

**Comment by xeno6696** [comment]
I think the conservative approach would be to re-insert it before `src/main/resources`

**Comment by xeno6696** [comment]
Then it restores previous functionality, we just add one more location.

**Comment by kwwall** [comment]
Works for me. I think this issue is assigned to you, so go for it.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
I must have missed this issue # in my commits earlier today... this one's fixed now...
