### ISSUE TITLE
addHeader in SecurityWrapperResponse has an arbitrary limit of 20 for the length of the Header name

### ISSUE THREAD

**Issue by dcabasson** [ESAPI/esapi-java-legacy#398]
We get a lot of warnings in our logs along the lines of :

```
017-07-13 11:47:04,010 WARN  [IntrusionDetector] (default task-49) [SECURITY FAILURE Anonymous:null@unknown -> /fsp/ds/efiling/IntrusionDetector] Input exceeds maximum allowed length of 20 by 2 characters: context=addHeader, type=HTTPHeaderName, orig=X-Content-Type-Options, input=X-Content-Type-Options: org.owasp.esapi.errors.ValidationException: addHeader: Invalid input. The maximum length of 20 characters was exceeded.
	at org.owasp.esapi.reference.validation.StringValidationRule.checkLength(StringValidationRule.java:214)
	at org.owasp.esapi.reference.validation.StringValidationRule.checkLength(StringValidationRule.java:229)
	at org.owasp.esapi.reference.validation.StringValidationRule.getValid(StringValidationRule.java:281)
	at org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:214)
	at org.owasp.esapi.reference.DefaultValidator.getValidInput(DefaultValidator.java:185)
	at org.owasp.esapi.filters.SecurityWrapperResponse.addHeader(SecurityWrapperResponse.java:173)

```

This issue was raised already in the mailing list under https://lists.owasp.org/pipermail/esapi-user/2016-January/001340.html. Kevin hints at a fix, but I can't see it in the codebase.

[SecurityWrapperResponse.java#addHeader](https://github.com/ESAPI/esapi-java-legacy/blob/2ff45b140a7e7b527a93bcdbc6bd7a1b3c188aca/src/main/java/org/owasp/esapi/filters/SecurityWrapperResponse.java#L168) still seem to have a hard coded limit of 20 on the length of the name of the header.

Is there a rationale why it's 20 and why X-Content-Type-Options or other headers such as Content-Security-Policy-Report-Only would be a security issue?

**Comment by planetlevel** [comment]
This should get updated. The rationale is to deny all and specifically allow what’s needed. But I don’t think those headers existed when ESAPI was created.

--Jeff

**Comment by xeno6696** [comment]
@kwwall looks like this issue got missed on #261.  I remember talking about it with you, but  we should definitely bump it up and get it in the upcoming point release.

**Comment by xeno6696** [comment]
To answer @dcabasson, I don't know why it was set to 20, but it's been that way since at least 2006.

**Comment by kwwall** [comment]
Matt,

I agree. There's a lot of similar things that all should probably be
configurable properties. We should take a broader look and address them all
at once instead of doing a one-off each time.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
Do you know if findbugs has a detector for magic #'s?  If not I can write a custom detector.  That said, where would we want the code for that to live?

**Comment by kwwall** [comment]
Dunno, I usually just resort to a grep regex. As long as you look for at
least double digits and then pipe it to 2nd grep to discard things that
look like dates, there usually is a tolerable number of false positives.

Aside: If you want to work on something findbugs related, see if you can
figure out why its Maven plugin is failing on 'mvn site'. I had to comment
it out in the latest pom.xml I committed. Probably easy for you.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
Actually, on inspecting this, we're relying on regexes.  Why didn't we choose to limit length by regexes instead of the concrete length check in the validator API?  Seems to me that it would have been much cleaner.  Technically speaking, as written we have literally two ways to check length with the API.  If I abstract that "20" and other magic numbers to property files... length check errors will have two possible sources of error.

**Comment by xeno6696** [comment]
Interesting.  Line 334 in ESAPI.properties actually has a value already for a max header size... looks like this just wasn't converted.
