### ISSUE TITLE
Refactor all "Magic Numbers" in the baseline to use ESAPI.properties configurations

### ISSUE THREAD

**Issue by xeno6696** [ESAPI/esapi-java-legacy#403]
Also includes removing all deprecated security configuration calls.

**Comment by xeno6696** [comment]
Using the regex `\(.*[0-9]+.*\)` to find the rest of these.

**Comment by kwwall** [comment]
What about hex-encoded ones? I know there are a few in the crypto, but I
think most of those need to be constants, not parameters.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
hardcoded numbers in crypto?  :-D

![image](https://user-images.githubusercontent.com/9502785/28747207-6b1a23ce-744e-11e7-9abd-06b7146dca4c.png)

**Comment by kwwall** [comment]
LOL. Sssshhhh. You don't reveal magicians' secrets.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by kwwall** [comment]
Besides, obviously not *my* code. I would have used 0x4 instead. Hex is
obviously more magical. ;-)

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
Jokes aside, just to be clear, I maybe misnamed the issue.  I'm hunting for any numbers that ought to be configurable.. not necessarily wrapped into well-named constants.  _looks at the codecs_ yeah, I'm fine with char values in there...

**Comment by xeno6696** [comment]
I've run into a host of nasty issues with unit tests after refactoring the crypto classes.  @kwwall , how much longer do you have on the crypto changes?

**Comment by kwwall** [comment]
Undo,. Please undo. More later.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
Well, in regards to your email, I was scratching my head that the crypto unit tests were failing because they were grabbing Strings from the recommended `SecurityConfiguration.getXProp()` instead of from the deprecated methods.  At any rate, duly rolled back.  So at this point the only changes that will be left are the magic numbers.  We can worry about getting rid of the deprecated methods later.  

(FWIW:  I had planned on delaying the merge until after you had pushed your crypto changes, but it sounds like the wiser path is just to have you handle the deprecation when you're ready.  )

**Comment by xeno6696** [comment]
Magic numbers are taken care of.  Ditching the part of the ticket that tacked on removing deprecated methods.
