### ISSUE TITLE
Update Travis CI configuration

### ISSUE THREAD

**Issue by augustd** [ESAPI/esapi-java-legacy#408]
Travis.yml (https://github.com/ESAPI/esapi-java-legacy/blob/develop/.travis.yml) currently points to bkimminich/esapi-java-legacy but that is not a valid repository on https://travis-ci.org: 

https://travis-ci.org/bkimminich/esapi-java-legacy
"The repository at bkimminich/esapi-java-legacy was not found."

**Comment by kwwall** [comment]
So does anyone want to "host" a Travis CI instance? Bjoern (@bkimminich) was kind enough to offer to set up the site originally. We probably should have either that go back to the Cloudbees Jenkins CI that preceded it. (The later should be referenced in an older version of README.md if anyone cares to go looking.)

**Comment by bkimminich** [comment]
The ESAPI org user must register on Travis-CI, set up a build and then simply replace my username with "ESAPI" in the configuration. If there are problems, I'm happy to help.

**Comment by augustd** [comment]
I have a Travis account, but it only allows me to access my OSS projects under https://github.com/augustd

Presumably, whoever owns the @ESAPI user account will have to setup Travis.

**Comment by kwwall** [comment]
I guess that would be me, but looks like Travis is insisting on using my GitHub account to authenticate, which is maybe acceptable (I'd prefer a separate, non-associated account), but it seems like Travis is requesting excessive GitHub privs to me (*manage* deployments, *write* commit status, *write* access to webhooks and services, That's _way_ more than I'm comfortable with. Does it have to be the OWNER of the @ESAPI account? If not, I'll create a more restricted account and maybe use it to execute CI builds on Travis. Surely there are more free Jenkins or Hudson services that would allow more or less the equivalent without such excessive permissions, isn't there? (Cloudbees seems to be a for-pay service, although they may have an exception for FOSS; I've not looked that closely.)

**Comment by kwwall** [comment]
I'm looking for someone who would like to take ownership of this. I really don't care which Continuous Integration tool is used (Jenkins, Hudson, Travis, etc.) but as you can see from my comments, I have objections giving Travis full admin GitHub rights. So maybe someone who knows more about CI could make a recommendation or what ESAPI should use and how we should set it up.

**Comment by kwwall** [comment]
@jackycct Could you look into this? I don't really care that much WHAT free hosted CI service that we use but we ought to be using one that at least compiles the code and runs the JUnit tests.
Now that @jeremiahjstacey  made some fixes in a JUnit test that was regularly failing about 15-25% of the time (it was timing out for various reasons and that has been fixed), I think we are ready to try this again. I am not picky about which we use, but as per my earlier https://github.com/ESAPI/esapi-java-legacy/issues/408#issuecomment-318783399, I do **_NOT_** want something that requires excessive GitHub privileges. I don't want the CI service making PRs, doing commits, etc.

**Comment by kwwall** [comment]
Setting this priority to 'high' because if ESAPI is to gain back any respect, we've got to get this working (along with making more regular releases, which I fully intend to do). However, I just don't have time to delve into this. What I don't want is a CI/CD pipeline that is going to require full ''owner'' role. I see no reason why any such access needs to allow 'commit / merge' access directly to this repo. If it only works that way, I think it is unacceptable. Any changes should come through PRs against a fork.

**Comment by kerberosmansour** [comment]
I got Travis running on a fork of ESAPI.

The CI is running but the build is failing tests (I know there is another issue on this), it could also be how I set it up, but I'm making progress.

So a couple of things:

1. Travis asks all these permissions as a catch all between it and GitHub, but **within** Travis you can add the restrictions you need.

2. I am still troubleshooting so I removed the coverity addon, just to get a build running per pull request.
Coverity themselves do **not** recommend it running for every build instead to have a separate branch for that:> Note: Coverity Scan's analysis should be run regularly to maintain your code quality, but not on each and every commit and branch. We recommend you use a branch named Coverity_scan, and push single commits to it when you'd like to trigger analysis.

3. You can create a GitHub specifically for this and us a group mail box as the primary email address so the dev team has access to it and can reset credentials if there is an issue, and it is not specific to one person etc.. you can then SSO that account with Coverity & Travis to minimize the concerns.

Here is a Travis Job that recently run:
https://travis-ci.org/ESAPI-CI/esapi-java-legacy/jobs/613069388?utm_medium=notification&utm_source=github_status

**Comment by kerberosmansour** [comment]
@kwwall it looks like the github account privileges without merge access is the "triage" account.
I will try it on throw away accounts to see if that would do, but would that be ok with you? Otherwise you would need to give Travis access to an account with merge capabilities and manage the privileges within Travis. @bkimminich do you have experience with this?

**Comment by kwwall** [comment]
@kerberosmansour  - Builds should be working now (after the merge). Any update on this?

**Comment by kerberosmansour** [comment]
I'll give it a try thanks!

**Comment by simon0117** [comment]
@kwwall made me aware of https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/ regarding GitHub Actions supporting CI/CD. I am going to investigate Actions as an alternative to this issue regarding Travis integration.

**Comment by kerberosmansour** [comment]
Thanks Simon!

**Comment by kwwall** [comment]
This was closed as part of PR #583. We are just using GitHub Actions instead of Travis-CI. A special shout-out to @simon0117 for taking this on.
