### ISSUE TITLE
issue with Filename encoding for executeSystemCommand

### ISSUE THREAD

**Issue by aaditriray** [ESAPI/esapi-java-legacy#424]
I have a requirement for compiling Java component from application itself.  I am trying to use DefaultExecutor.executeSystemCommand(File executable, List params) to execute "javac" command and trying to pass the absolute file path within the params. However with the default (reference ) implementation of DefaultEncoder.encodeForOS(Codec codec, String input) the file path is being encoded with is not recognized by OS. 

With my own implementation having all required special character ( for Filepath) as immune character then it works fine.

private final static char[] IMMUNE_OS = { '-' , '\\' , '.', ':', '/' ,'_' , ';' };

I am wondering what could be the suggested approach to pass an absolute Filepath for execution of a system command using ESAPI.Executor.

**Comment by kwwall** [comment]
@aaditriray I'm not sure what you are exactly trying to accomplish here (a short code snippet or a JUnit test that is failing would be nice to attach!), but you definitely don't want to add all those characters to the 'immune' list regardless of OS. The idea is that some input parameters to whatever command that you are executing are not trusted. So if you allow (say) a ';' character in the IMMUNE_OS list for UNIX, then an attacker who as control of the input could inject an additional command which is probably not something that is desired. Thus that character needs to be escaped. I could make similar arguments for most of the others that you added. (Underscore should be save though. We may want to consider adding it if isn't already considered as an alphanumeric character; too lazy to check at the moment.)

**Comment by xeno6696** [comment]
Where does the filepath originate?  If it's coming from the user, this is all sorts of dangerous.  

Otherwise @kwwall is right, can't do much to help you without a code sample... that said, this question seems more appropriate for you to ask in the mailing list.  Checkout the README.md at the root of this repo.

**Comment by kwwall** [comment]
For the record, I second closing this. More information was asked and never received.

**Comment by kwwall** [comment]
@xeno6696 Although I am beginning to wonder perhaps we should either change these various IMMUNE lists to protected and allow developers to subclass them or provide a public method on Encoder to allow one to set the various IMMUNE lists. (If `DefaultEncoder` weren't implemented as a singleton, I probably would have done the latter a while ago, but with it being a singleton, I think it's just too dangerous and devs would be apt to shoot themselves in the foot. But maybe something to consider once we burn the singletons to the ground.)
