### ISSUE TITLE
Project build error: Non-resolvable parent POM for org.owasp.esapi:esapi:2.1.0.2-SNAPSHOT: Could not transfer artifact 

### ISSUE THREAD

**Issue by rajeshbairagoni4** [ESAPI/esapi-java-legacy#425]
Getting "Project build error: Non-resolvable parent POM for org.owasp.esapi:esapi:2.1.0.2-SNAPSHOT: Could not transfer artifact  org.sonatype.oss:oss-parent:pom:5 from/to central (https://repo.maven.apache.org/maven2): connect timed out and  'parent.relativePath' points at wrong local POM" in pom.xml which is cloned from github esapi-java-legacy developer branch.

Can anyone please help me to resolve this and build jar file from the source ?

**Comment by kwwall** [comment]
That's a "SNAPSHOT". We don't put those in Maven Central. The last ESAPI
version there is 2.1.0.1.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
Kevin is correct.  If you want to build for the latest version, checkout the 2.1.0.1 tag and then build.  

If you want to compile HEAD as it is, change the version to something custom, like 2.1.0.rajesh

**Comment by xeno6696** [comment]
@kwwall is correct.  If you want to compile against a particular version, you need to checkout that tag in and build it that way.
