### ISSUE TITLE
Tighten ESAPI defaults to disallow dubious file suffixes

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#439]
The property `HttpUtilities.ApprovedUploadExtensions` in the **ESAPI.properties** file defines a white-list of allowed file suffixes for file uploads.  By default, it allows several questionable file suffixes that most companies would generally not allow to be uploaded to their web sites. We need to pick a safer subset for the default (in part, because so few seem to change the default).

The current default is:
`HttpUtilities.ApprovedUploadExtensions=.zip,.pdf,.doc,.docx,.ppt,.pptx,.tar,.gz,.tgz,.rar,.war,.jar,.ear,.xls,.rtf,.properties,.java,.class,.txt,.xml,.jsp,.jsf,.exe,.dll`

At the very least, we should probably remove from this list files that, as a rule, consist of executable code. At a minimum, I propose that we eliminate the following:
`.war, .jar, .ear, .class, .jsp, .jsf, .exe, and .dll`

If it were up to me, I would only keep these file suffixes:

`.pdf, .doc, .docx, .ppt, .pptx, .xls, .xlsx, .rtf, .txt`

Anyhow, I will leave open this up for comment. Keep in mind that any given application may change the ESAPI.properties as they wish, but since ESAPI is a library providing security controls and since developers seem to so often leave the ESAPI.properties file as-is, I do think we need a reasonably safe set of defaults.

Note that these file suffixes do not really restrict the actual file type. For example, someone could rename the file "malware.exe" to "readme.docx" and by doing so, sneak it past these checks. (Note that GitHub issue #373 discusses that particular issue and some approaches in dealing with it.)

**Comment by planetlevel** [comment]
Totally agree.  How the heck did that happen?

--Jeff

**Comment by ozkanpakdil** [comment]
I agree. also why not add .jpg .png . It is very common people upload some images at some point.

**Comment by gumshoe2020** [comment]
The list you proposed plus jpg and png seems solid to me too.

**Comment by agronosky** [comment]
I love the approach of making the defaults safe(r). If people want to shoot themselves in the foot (uploading .class files etc) they should have to figure out how to load the gun for themselves. ;-)

+1 in favor of adding .jpg, .png to the default white list

**Comment by kwwall** [comment]
I see also that in `DefaultSecurityConfiguration.getAllowedFileExtensions()` there is a default set of file suffixes:
```
    public List<String> getAllowedFileExtensions() {
    	    String def = ".zip,.pdf,.tar,.gz,.xls,.properties,.txt,.xml";
            String[] extList = getESAPIProperty(APPROVED_UPLOAD_EXTENSIONS,def).split(",");
            return Arrays.asList(extList);
    }
```

in case `HttpUtilities.ApprovedUploadExtensions` is not set in **ESAPI.properties**. I am going to change this to a really minimalist list of:
```
   String def = ".pdf,.txt,.jpg,.png";
```

as well as part of this change.
