### ISSUE TITLE
esapi.tld 

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#44]
_From [chrisisbeef](https://code.google.com/u/chrisisbeef/) on October 14, 2009 15:18:40_

Greetings,

I was wondering about the current state of the ESAPI JSP tags. I'm
looking to use them from JSP documents (jspx) and have had some issues.

Specifically, the TLD in the 1.4 release incorrectly sets the URI to be
" http://struts.apache.org/tags-html ". Is there a URI that this should
be changed to instead? I patched it with the URL for the wiki page and
was able to get it working. The tld is not included in the final JAR so
you have to add a taglib declaration to the deployment descriptor and
include the TLD explicitly.

I'm not seeing a TLD in the 2.0 stuff at all.

On another note, I'm interested in getting involved some in the
project. I'm not very knowledgeable about JSP but I can figure it out
if that would be desired. Other than that, where would a good place to
start be? Getting units working? CPD/FindBugs/PMD fixes?

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=34_

**Comment by kwwall** [comment]
The label 'Release-2.0' was _only_ used for this issue. so I changed it to 'Milestone-Release2.0' so I can delete the 'Release-2.0' label. (I wasn't sure of the effect if I deleted it and it referred to an issue, even though that issue is closed.)
