### ISSUE TITLE
can't generate MasterKey / MasterSalt 

### ISSUE THREAD

**Issue by chammaksharma** [ESAPI/esapi-java-legacy#447]
After running the script setMasterKey where can we see the MasterKey generated. I did not see it in the ESAPIProperties file. Decryption and Encryption was not happening when trying to use DefaultEncryptedProperties.

**Comment by kwwall** [comment]
This is not the forum for asking questions. Use the one of the ESAPI mailing lists or (as a last resort) StackOverflow for that.

However, the intent of the `setMasterKey.sh` script is not to generate a key and add it to the **ESAPI.properties** file. Rather it generates a random key and salt, prints it to stdout, and clearly precedes that with a comment that tells you to _copy-and-paste_ those values into your **ESAPI.properties** file.
