### ISSUE TITLE
about code eclipse formatter template question

### ISSUE THREAD

**Issue by keyouhui** [ESAPI/esapi-java-legacy#454]
Anyone have the esapi-java-legacy eclipse code formatter template file?

if want modify some code ,need formatter template, where can download the formatter file ?

if and one have the eclipse formatter template file, pls tell me.thank you very much.
my email address : keyouhui@huawei.com.

**Comment by keyouhui** [comment]
it is eclipse code Java Code Style --> Formatter this template.
I want get the esapi-java-legacy formatter .
thank you very much.

**Comment by kwwall** [comment]
@keyouhui Just wondering, are you possibly thinking of this:
https://github.com/rexcardan/VarianDeveloper/wiki/Getting-Started-With-Eclipse-Scripting-API-(ESAPI)-v11

(A different ESAPI. That is, I think this is a case of OWASP ESAPI are not the droids you are looking for.)

**Comment by kwwall** [comment]
Please ask any further ESAPI related questions as per instructions in the README.md. Thanks.
