### ISSUE TITLE
when run jetty ,can not find  esapi\ESAPI.properties

### ISSUE THREAD

**Issue by JasperXgwang** [ESAPI/esapi-java-legacy#457]
when run jetty  there are exception `can not find  esapi\ESAPI.properties`

because `ClassLoader.getSystemClassLoader()` from jvm classloader，not jetty WebAppClassLoader

so use `Thread.currentThread().getContextClassLoader()`  fix this problem

[details](https://jasperxgwang.github.io/2018/11/01/%E5%85%B3%E4%BA%8EclassPath%E8%8E%B7%E5%8F%96%E8%B5%84%E6%BA%90%E6%96%87%E4%BB%B6%E9%97%AE%E9%A2%98/)

**Comment by xeno6696** [comment]
Fixed in pr 456
