### ISSUE TITLE
Bump ESAPI release # to 2.2.0.0

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#471]
There are two major and potentially impactful changes in the next planned release of ESAPI (exact release date, TBD):

- Upgrade to require JDK 7 or later. JDK 6 is no longer supported by ESAPI.

- Upgrade to require Java Servlet API 3.0.1 or later. Previously only version 2.5 of the servlet API was required.

For this reason, we have decided to call the next release 2.2.0.0 rather than 2.1.0.2. The pom.xml file and various documentation files and the OWASP ESAPI wiki page will be updated in accordance with this (as part of the release for the pom.xml and shortly afterwards for the others).

**Comment by awshanks** [comment]
Do we have a timeframe for release?

**Comment by kwwall** [comment]
As soon as I can figure out the Maven magic to make it happen. If you can help "debug" the release process, let us know.

**Comment by kwwall** [comment]
Closed via PR #464 and commit 8ffe783
