### ISSUE TITLE
Issue while decoding non-BMP characters

### ISSUE THREAD

**Issue by anshumanp2902** [ESAPI/esapi-java-legacy#481]
I am using a HTML sanitizer which internally uses org.owasp.html.Encoding.encodeHtmlOnto(String, Appendable, String) to encode non-BMP character such as '😉'(`&#x1f609;`). 
For decoding this, I am using org.owasp.esapi.codecs.HTMLEntityCodec which internally calls org.owasp.esapi.codecs.HTMLEntityCodec.parseHex(PushbackString). Since the encoded hex value 1f609 is a supplementary codepoint constructed from surrogate pairs(https://docs.oracle.com/javase/tutorial/i18n/text/supplementaryChars.html), when the method tries to decode it using  -

int i = Integer.parseInt(sb.toString(), 16);
            if (Character.isValidCodePoint(i)) {
                return (char) i;
            }

it returns a single character which is incorrect.

Ideally it should - 
if(Character.isSupplementaryCodePoint(codepoint))
{
		char[] codeToChararr  = Character.toChars(codepoint);
		StringBuilder builder = new StringBuilder();
		for(char c:codeToChararr)
		{
			builder.append(c);
		}

//TODO : Change the return type to string or character array
} else {
 int i = Integer.parseInt(sb.toString(), 16);
            if (Character.isValidCodePoint(i)) {
                return (char) i;
            }
}

Or something like this. 

I found this comment (https://github.com/esapi/esapi-java-legacy/issues/300#issuecomment-320171269) where someone talked about adding some fixes around decoding. But I could not find any fix for this issue.
Please check this and let me know if there is already a fix around this issue present or it is working as designed.

**Comment by xeno6696** [comment]
This was fixed in #300 and will be available in the imminent release.

**Comment by kwwall** [comment]
@anshumanp2902 The candidate release, 2.2.0.0-RC2, was just pushed to Maven Central yesterday.

**Comment by anshumanp2902** [comment]
Thanks.. This release seems to have solved the problem
