### ISSUE TITLE
wrong regex validation

### ISSUE THREAD

**Issue by iberbeu** [ESAPI/esapi-java-legacy#493]
When I call this method

`ESAPI.validator().isValidInput("RelayState", "https://myserver.com/web/userlist/user/my%40email.com", "URL", 2000, true);`

I get false. If I call getValidInput I get an error that says that my input must conform the regex ^(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\:\'\/\\\+=&amp;%\$#_]*)?$

But my input does conform that regex. The problem is in the character "%40" which replaces an "@". If I remove this character it works. Is there a way that esapi does this validation properly?

**Comment by jeremiahjstacey** [comment]
Looking at the implementation, your parameters are as follows:
  * context = "RelayState"
  * input = "https://myserver.com/web/userlist/user/my%40email.com"
  * type = "URL"
  * maxLength = 2000
  * allowNull = true

The important ones here are input and type. 

Following the call chain of the DefaultValidator implementation, we can see that it eventually ends up building a StringValidationRule to check your input against a given encoder.

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/reference/DefaultValidator.java
(around line 209)

In addition, any whitelist patterns are added from the the SecurityConfiguration context.  I believe it is this whitelist content that is causing your troubles.

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/reference/DefaultSecurityConfiguration.java
(around line 1157)

The whitelist is derived from the type field you provide as "URL".  The DefaultSecurityConfiguration class prefixes "Validation." to the type, and then looks at the ESAPI.properties file for the regex to compare against.

When I look at the test-scope ESAPI.properties I am not finding an entry for Validation.URL in the baseline.

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/test/resources/esapi/ESAPI.properties


At this point I am assuming that your environment has extended the type list from the baseline.  If Validation.URL does not exist you would see an IllegalArgumentException from the DefaultValidator.

 I think you may just need to update the regex in ESAPI.properties for Validation.URL to work like you expect.

**Comment by iberbeu** [comment]
Hi @jeremiahjstacey ,

thank you very much. That has solved the problem. In the end I changed the type to HTTPURL which is a valide Validator and know the string is validated correctly.

Thank you very much for your help

**Comment by kwwall** [comment]
@jeremiahjstacey  @iberbeu Actually, ESAPI would normally find Validation.URL in the "validation.properties" file. Depending what version you picked up, the one intended for "production" is in https://github.com/ESAPI/esapi-java-legacy/blob/develop/configuration/esapi/validation.properties.
There you will find this (line 26 at the time of this writing, when the current value is set thusly):

`Validator.URL=^(ht|f)tp(s?)\\:\\/\\/[0-9a-zA-Z]([-.\\w]*[0-9a-zA-Z])*(:(0-9)*)*(\\/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'\\/\\\\\\+=&;%\\$#_]*)?$`
