### ISSUE TITLE
Encoded input is not treated as an attack

### ISSUE THREAD

**Issue by rabeeeabif** [ESAPI/esapi-java-legacy#517]
behavior of `getValidInput` method in class `DefaultValidator` has been changed between versions `2.1.0.1` and `2.2.0.0`

**Example** :
`ESAPI.validator().isValidInput("QueryString", "value=%3Cscript%3Ealert(1)%3C%2Fscript%3E", 30000, true)`
**Expected**: return false
**Actual** ( version 2.1.0.1): returns false
**Actual** ( version 2.2.0.0): returns true

**Comment by jeremiahjstacey** [comment]
I have not created any additional tests at this time, but this could be related to the work for https://github.com/ESAPI/esapi-java-legacy/issues/476
https://github.com/ESAPI/esapi-java-legacy/commit/3475e86d2c2828fb944b2f3fb8cc0e2639a23510

This is the closest content that I can see that may have impacted this behavior.

The default value of the canonicalize parameter in the  DefaultValidator is set to true, which should default to performing canonicalization through the DefaultEncoder.  The StringValidationRule is the class that actually handles the check.

I would start pulling this thread and see if I overlooked something in the implementation.

**Comment by rabeeeabif** [comment]
I looked at `StringValidationRule.getValid` and it looks that the result of `encoder.canonicalize(input)` is not validated , i believe that happened unintentionally

**Comment by jeremiahjstacey** [comment]
At that point, it would be the DefaultEncoder that is allowing the mixedEncoding content.  StringValidator doesn't  contain additional logic outside of canonicalizing the string.

From a quick scan of the DefaultEncoder file history I'm not seeing any functional changes that would have caused this type of behavioral difference.

Can you debug the execution of DefaultEncoder.canonicalize(String, boolean, boolean) and inspect what the two boolean values are?

Based on what I think I understand, there's a possibility this is a configuration issue in the ESAPI.properties file that's being used at runtime.  The two properties that drive the booleans are 
* Encoder.AllowMultipleEncoding
* Encoder.AllowMixedEncoding

I would also be interested in knowing which codecs are being used in the DefaultEncoder, and the order in which they are defined.
That is also in ESAPI.properties as 
* Encoder.DefaultCodecList

**Comment by xeno6696** [comment]
Just want to leave my 2 cents here:  This alarming but NOT critical!  

You can have a 95% defense against XSS with proper output encoding alone.  I'm researching this issue, but as long as your developers are escaping for the correct context, this is ultimately a low bug.  Preventing XSS based on regex input validation is a fool's errand.

**Comment by rabeeeabif** [comment]
I got frustrated about this issue i found the issue that changed the behavior which was #284 .
 #xeno6696 should i close it ?

**Comment by xeno6696** [comment]
Well first off, thank you so much for the passion and care you've attended to this!  I'd love to have you for a regular contributor!  We still have many bugs to fix before we can realistically begin ESAPI 3.0!  

My gut reaction is to close this but caution begs some discussion @rabeeeabif .  Did you narrow it down to a particular commit?

**Comment by xeno6696** [comment]
I'm having problems right now getting this to compile even with java 1.7

**Comment by xeno6696** [comment]
So I wrote this unit test in ValidatorTest.java:

```
    public void testURIEntityInQueryString(){
    	Validator v = ESAPI.validator();
    	boolean isValid = v.isValidInput("QueryString", "value=%3Cscript%3Ealert(1)%3C%2Fscript%3E", "Query", 30000, true);
    	assertFalse(isValid);
    }
```

This works as expected, coming back false.  

I tried this version of the test:

```
    public void testURIEntityInQueryString(){
    	Validator v = ESAPI.validator();
    	boolean isValid = v.isValidInput("QueryString", "value=<script>alert(1);</script>", "Query", 30000, true);
    	assertFalse(isValid);
    }
```

This also comes back as false.

**Comment by OrionR0** [comment]
@xeno6696 In response to your post to my code comment thread, the specific regex used in the project I referenced is ^[^<>]*. The expected behavior in said project's unit tests is for getValidInput to throw an error when using that regex and passing the following string as input: %2d%2d%3e%3c%2f%73%43%72%49%70%54%3e%3c%73%43%72%49%70%54%3e%61%6c%65%72%74%28%31%36%35%38%38%29%3c%2f%73%43%72%49%70%54%3e

**Comment by xeno6696** [comment]
So I'm using a regex debugging tool, and my debug output is this:

![image](https://user-images.githubusercontent.com/9502785/94085978-795d6980-fdbe-11ea-95cd-f0639e03a017.png)

What you have here is a case of your regex NOT doing what you'd expect.  I would NOT expect a mixed or multiple encoding error here, nor would I expect your input to fail that regex.

**Comment by xeno6696** [comment]
See construction output:

![image](https://user-images.githubusercontent.com/9502785/94086135-e113b480-fdbe-11ea-833e-78c3fc1c91a3.png)

**Comment by xeno6696** [comment]
Oh wait a second...

**Comment by xeno6696** [comment]
Okay yeah I think you found the bug.

**Comment by xeno6696** [comment]
You'd correctly expect the canonicalized regex to get passed to the method and you found the single corner case that I was concerned about.  WELL DONE!

**Comment by xeno6696** [comment]
Only.... it's coming back false:

```
    public void testRegex(){
    	Validator v = ESAPI.validator();
    	boolean isValid = v.isValidInput("RegexString", "%2d%2d%3e%3c%2f%73%43%72%49%70%54%3e%3c%73%43%72%49%70%54%3e%61%6c%65%72%74%28%31%36%35%38%38%29%3c%2f%73%43%72%49%70%54%3e", "Query", 30000, true);
    	assertFalse(isValid);
    }
```
This unit test correctly punts the input string.

**Comment by xeno6696** [comment]
Some sleuthing to be done here:

```
    public void testRegexWithGetValid() throws Exception {
    	Validator v = ESAPI.validator();
    	String foo = v.getValidInput("RegexString", "%2d%2d%3e%3c%2f%73%43%72%49%70%54%3e%3c%73%43%72%49%70%54%3e%61%6c%65%72%74%28%31%36%35%38%38%29%3c%2f%73%43%72%49%70%54%3e", "Query", 30000, true);
    	fail("Should never reach here.");
    	
    }

```

Please community, this unit test breaks alot of rules, but it correctly demonstrates the problem I think.  @OrionR0 do you agree?

**Comment by xeno6696** [comment]
This is why you don't stream of program issues folks.  I was passing the wrong regex selector, the failing unit tests are now:

```
    public void testRegex(){
    	Validator v = ESAPI.validator();
    	boolean isValid = v.isValidInput("RegexString", "%2d%2d%3e%3c%2f%73%43%72%49%70%54%3e%3c%73%43%72%49%70%54%3e%61%6c%65%72%74%28%31%36%35%38%38%29%3c%2f%73%43%72%49%70%54%3e", "RegexString", 30000, true);
    	assertFalse(isValid);
    }
    
    public void testRegexWithGetValid() throws Exception {
    	Validator v = ESAPI.validator();
    	String foo = v.getValidInput("RegexString", "%2d%2d%3e%3c%2f%73%43%72%49%70%54%3e%3c%73%43%72%49%70%54%3e%61%6c%65%72%74%28%31%36%35%38%38%29%3c%2f%73%43%72%49%70%54%3e", "RegexString", 30000, true);
    	fail("Should never reach here.");
    	
    }

```

**Comment by xeno6696** [comment]
Confirmed, flipping from input to data in the regex resolves the issue, I just need to clean up the second unit test now.  

Thanks for putting up with me @OrionR0

**Comment by jeremiahjstacey** [comment]
This may be related to updates in the HTML Validation Rule?
Check the behavior you're testing with the `Validator.HtmlValidationAction` property to set to both 'clean' and 'throw'.
The difference may be a result of a corrected condition.

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/reference/validation/HTMLValidationRule.java
See method `legacyHtmlValidation`

https://github.com/ESAPI/esapi-java-legacy/blob/develop/configuration/esapi/ESAPI.properties
And the default value of `Validator.HtmlValidationAction` (around line 537)

**Comment by OrionR0** [comment]
@jeremiahjstacey Whether using 'clean' or 'throw' the relevant unit tests still failed. I think xeno6696 has this now.

**Comment by OrionR0** [comment]
@xeno6696 Another thought on this... instead of passing only data, would passing both input and data as it was done in the past make for prettier logs? There's another method that takes the extra parameter.

**Comment by xeno6696** [comment]
Yeah I can do that--I'll be honest in that I wasn't aware the 3-param method was used mainly for logging purposes.  Wish I had you on the code review back in 2017 lol.
