### ISSUE TITLE
javadoc corrections for Encoder.canonicalize()

### ISSUE THREAD

**Issue by pachulo** [ESAPI/esapi-java-legacy#522]
Hi! I'm trying to understand how exactly the method `Encoder.canonicalize()`  works and for that I'm reading the javadocs from here:

- https://static.javadoc.io/org.owasp.esapi/esapi/2.2.0.0/org/owasp/esapi/Encoder.html#canonicalize-java.lang.String-boolean-boolean-

But when testing some code examples, I found things that I don't really understand; for example:

> In ESAPI, the Validator uses the canonicalize method before it does validation. So all you need to do is to validate as normal and you'll be protected against a host of encoded attacks.
>      String input = request.getParameter( "name" );
>      String name = ESAPI.validator().isValidInput( "test", input, "FirstName", 20, false);

If I read correctly, `ESAPI.validator().isValidInput()` returns a `boolean`, not a `String`. I'm guessing that the correct method to call in the last line of the example should be...`ESAPI.validator().getValidInput()` ?

And the same would apply here:

> However, the default canonicalize() method only decodes HTMLEntity, percent (URL) encoding, and JavaScript encoding. If you'd like to use a custom canonicalizer with your validator, that's pretty easy too.
>      ... setup custom encoder as above
>      Validator validator = new DefaultValidator( encoder );
>      String input = request.getParameter( "name" );
>      String name = validator.isValidInput( "test", input, "name", 20, false);

Also, in this example:

> This method allows you to override the default behavior by directly specifying whether to restrict multiple or mixed encoding. Even if you disable restrictions, you'll still get warning messages in the log about each multiple encoding and mixed encoding received.
>      // disabling strict mode to allow mixed encoding
>      String url = ESAPI.encoder().canonicalize( request.getParameter("url"), false, false);

Shouldn't the correct call be `ESAPI.encoder().canonicalize( request.getParameter("url"), true, true);`

Am I getting something wrong?

Thanks!

**Comment by kwwall** [comment]
Specifically, this is about fixing the Javadoc for the 3 argument version of Encoder.canonicalize() as documented here: https://static.javadoc.io/org.owasp.esapi/esapi/2.2.0.0/org/owasp/esapi/Encoder.html#canonicalize-java.lang.String-boolean-boolean-

@pachulo is indeed correct and the first 2 cases should be using Validator.getValidInput() rather than Validator.isValidInput().

**Comment by pachulo** [comment]
> Specifically, this is about fixing the Javadoc for the 3 argument version of Encoder.canonicalize()

Thanks @kwwall I've updated the link on the comment!

> @pachulo is indeed correct and the first 2 cases should be using Validator.getValidInput() rather than Validator.isValidInput().

What do you think about the 3rd example?

**Comment by xeno6696** [comment]
> This method allows you to override the default behavior by directly specifying whether to restrict multiple or mixed encoding. Even if you disable restrictions, you'll still get warning messages in the log about each multiple encoding and mixed encoding received.
// disabling strict mode to allow mixed encoding
String url = ESAPI.encoder().canonicalize( request.getParameter("url"), false, false);


Don't do this.  I'm pretty sure that when I added proper URI canonicalization that I didn't capture THAT particular use case.  

Use DefaultEncoder.getCanonicalizedURI() and then apply the URL regex that you've customized from there.

**Comment by kwwall** [comment]
@xeno6696 - Even if you think that  the change I suggested should not be documented, I think that this javadoc needs to be revised to mention to use Encoder.getCanonicalizedURI() instead. I don't think that it is obvious that there should be an exclusion here for URIs.

**Comment by xeno6696** [comment]
I agree @kwwall , I need to investigate this further, and we should update the documentation.  I think I maybe misread something above, i didn't mean "don't document," just "Don't use the library this way."

**Comment by kwwall** [comment]
@xeno6696 - Have you ever had the chance to look at this? I am preparing a PR that has some small miscellaneous updates, one of which are updates to the Encoder interface and I knew what to document here, I will add it in this PR.

**Comment by kwwall** [comment]
@xeno6696 - I think that we can mark this as closed not that we have updated the Javadoc for the 3-argument `canonicalize()` method. (We added that **WARNING** and refer to using `Encoder.getCanonicalizedURI(URI dirtyUri)` instead. See example under that method in https://www.javadoc.io/doc/org.owasp.esapi/esapi/latest/org/owasp/esapi/Encoder.html for details.)

Do you agree? If so, I will mark this as closed (or you can) and note it as such in the forthcoming 2.2.1.0 release notes.

**Comment by kwwall** [comment]
@xeno6696 - Hmm. I'm pretty sure that PR #553 closed this, but maybe I meant fix issue #522 instead of (or in addition to?) #522. I'm going to mark this as closed. Feel free to re-open if you disagree. Thanks.

**Comment by xeno6696** [comment]
I thought I *had* closed this myself.  No worries, I concur.

**Comment by kwwall** [comment]
I'm beginning to think that the autoclose comments don't work if the fix is from a PR originating from a forked repo. At the very least it seems very arbitrary to me.
