### ISSUE TITLE
Apply default logging content to SLF4J messages

### ISSUE THREAD

**Issue by jeremiahjstacey** [ESAPI/esapi-java-legacy#530]
### Problem Description

The SLF4J logger implementation is lacking the default prefix content applied by other ESAPI Logger implementations.

The two existing logger implementations, Log4J and Java, both prefix information to the message being logged prior to delegating to the related Logger implementation.

The desired output string should appear in the format:
`[EVENT_TYPE USER_ACCOUNT_NAME:SESSION_ID@REMOTE_CONNECTION_INFO -> SERVER_CONNECTION_INFO/APPLICATION_NAME/MODULE_NAME] + CLEAN_MESSAGE_STRING`

`APPLICATION_NAME/MODULE_NAME` is optional based on the configured value of `ESAPI.securityConfiguration().getLogApplicationName()`

The value of `APPLICATION_NAME` is determined by the value of `ESAPI.securityConfiguration().getApplicationName()`

The value of `MODULE_NAME` should follow the Log4JLogger implementation and use the Logger's name.

`SERVER_CONNECTION_INFO` is optional based on the configured value of `ESAPI.securityConfiguration().getLogServerIP()`

`SERVER_CONNECTION_INFO` is assembled as follows:
`ESAPI.currentRequest().getLocalAddr()).append(":").append(ESAPI.currentRequest().getLocalPort()`

### Implementation Strategy

1) rename the 'scrubber' classes to 'logMutator'
2) Update the logMutator interface to accept necessary inputs to allow content to be assembled
3) create new implementation(s) that will derive all of the desired data and prefix it to the provided message.
4) Inside of the SLF4JFactory, add the new implementation(s) to the chain of log mutation (previously scrubbers).

**Comment by jeremiahjstacey** [comment]
@kwwall From the comments on PR #529 the values of `appname`, `username`, and `clientIP` were specifically requested.

https://github.com/ESAPI/esapi-java-legacy/pull/529#issuecomment-560954427

I'm pretty sure this is what you were asking for in the comment and I hadn't fully understood what the content would entail.  It is a little more work than I had originally scoped just due to the number of aggregate sources, but not to a significant scale.  I intend to target that output format in this effort.

I would appreciate confirmation that this is what is desired from this task:

`[EVENT_TYPE USER_ACCOUNT_NAME:SESSION_ID@REMOTE_CONNECTION_INFO -> SERVER_CONNECTION_INFO/APPLICATION_NAME/MODULE_NAME]`

**Comment by kwwall** [comment]
@jeremiahjstacey - Yes, I think this:

> [EVENT_TYPE USER_ACCOUNT_NAME:SESSION_ID@REMOTE_CONNECTION_INFO -> SERVER_CONNECTION_INFO/APPLICATION_NAME/MODULE_NAME]

looks like what we want to capture. We can make changes to disable some of those fields (as per Issue #527 and PR #529) after this is in place.

**Comment by jeremiahjstacey** [comment]
@kwwall - I have made progress on the implementation.  It is a little different than what I had initially proposed, but I believe it will be more maintainable.  Moving into the unit tests, I believe I have captured the behavior of the current implementations.  Before I verify these cases, I would like to confirm that these cases are the desired end state. 


### For the client portion of the message:  
   `USER_ACCOUNT_NAME:SESSION_ID@REMOTE_CONNECTION_INFO`
  - If the user evaluates to null, the message is an empty string
  - If the user is populated and the request is null, the result would be `USER_ACCOUNT_NAME:@REMOTE_CONNECTION_INFO`
  - If the 'logUser' boolean value is set to false, the message is an empty String. (this is the property being discussed in the other task)
  

### For the server portion of the message:  
   `SERVER_CONNECTION_INFO/APPLICATION_NAME/MODULE_NAME`
  - If the request is null, and 'log_application' boolean is `true` the result would be `/APPLICATION_NAME/MODULE_NAME`
  - If the request is null, and 'log_application' boolean is `false` the result would be `/MODULE_NAME`
   - If the request is not null and 'log_server_info' is `false`, and 'log_application' boolean is `true` the result would be `/APPLICATION_NAME/MODULE_NAME`
  - If the request is not null and 'log_server_info' is `false`, and 'log_application' boolean is `false` the result would be `/MODULE_NAME`
  - If the request is not null and 'log_server_info' is `true`, and 'log_application' boolean is `true` the result would be `SERVER_CONNECTION_INFO/APPLICATION_NAME/MODULE_NAME`
  - If the request is not null and 'log_server_info' is `true`, and 'log_application' boolean is `false` the result would be `SERVER_CONNECTION_INFO/MODULE_NAME`

**Comment by jeremiahjstacey** [comment]
https://github.com/jeremiahjstacey/esapi-java-legacy-dev/commit/4a87d5692ebf9dfd23015f82e801c35c0725f554  Inital commit of the structure. 

I still need to update the existing unit tests and write new ones, but it at least illustrates the intent.

**Comment by jeremiahjstacey** [comment]
@kwwall @xeno6696   Should this data be appended to the message before or after the string is cleaned?  In the Java and Log4J implementations it is appended post-clean, but I kind of think that it would make sense to do it before.  Mostly since it's feasible that the Application name may contain characters that should be encoded consistently with the rest of the message?

**Comment by jeremiahjstacey** [comment]
I was making good progress, but now am stuck in testing.   For whatever reason I am unable to mock the `org.owasp.esapi.User` interface. At least it is the last piece of the implementation.  All other tests and updates have been pushed to my fork.

**Comment by jeremiahjstacey** [comment]
I found what I need for the tests.  I need to explicitly exclude the 'javax.security.*" content from PowerMock scope.

https://www.gyanblog.com/gyan/20-linkage-error-loader-constraint-violation-junit-test-case-development-issue/

```
@RunWith(PowerMockRunner.class)
@PrepareForTest({ESAPI.class})
@PowerMockIgnore("javax.security.*") //Required since User extends javax.security.Principal
public class ClientInfoSupplierTest {
```

**Comment by jeremiahjstacey** [comment]
Initial implementation & tests are now complete on my fork.
- All tests pass, except the ValidatorTest content identified in Issue #521 

Pending feedback 
- agreed output format
  - https://github.com/ESAPI/esapi-java-legacy/issues/530#issuecomment-562801235
- the order of operations for appending/cleaning
  - https://github.com/ESAPI/esapi-java-legacy/issues/530#issuecomment-562846107

**Comment by kwwall** [comment]
> ### For the client portion of the message:
> 
> `USER_ACCOUNT_NAME:SESSION_ID@REMOTE_CONNECTION_INFO`
> 
>     * If the user evaluates to null, the message is an empty string

If the user is null, I think the string that is supposed to get used is "Anonymous", not the empty string.

**Comment by kwwall** [comment]
@jeremiahjstacey wrote:


> @kwwall @xeno6696 Should this data be appended to the message before or after the string is cleaned? In the Java and Log4J implementations it is appended post-clean, but I kind of think that it would make sense to do it before. Mostly since it's feasible that the Application name may contain characters that should be encoded consistently with the rest of the message?

It's probably okay to do this before cleaning. Think of it this way. Each of those data items you are prepending to the log message are considered "tainted", but for most of them the "taint source" is either from the ESAPI.properties file (which we pretty must have to consider as trusted) or from the ESAPI code itself. For example,
`	private static Logger logger = ESAPI.getLogger("JavaEncryptor");`
which also has to be trusted. The two others are the user name and the client IP address. I'm not seeing how the client IP address could be unsafe, so I think that only leaves the user name. So either the user name will be null (so that "Anonymous" should be inserted) or it will be an actual verified user name. I think that the default regex rules and default implementation in ESAPI probably insists (I haven't verified) that the user name only consists of 1 or more alphanumeric characters. An application _could_ change that,but certainly should not. If a dev team allows all sorts of user names like "<script>alert(1)</script>" then they deserve what they get. So I'm okay with you doing this pre-cleaning.  Did I miss anything? Maybe. But think of everything that can go into a log message as tainted and which of those pieces have untrusted tainted sources vs trusted sources.

**Comment by kwwall** [comment]
@jeremiahjstacey  - BTW, did you do your work on this under the 'develop' branch of your fork or some other branch? I just want to make sure I'm looking at the right code.

**Comment by jeremiahjstacey** [comment]
It's under the branch Issue_530
https://github.com/jeremiahjstacey/esapi-java-legacy-dev/tree/Issue_530

**Comment by jeremiahjstacey** [comment]
@kwwall  I'd like to follow up more on the user value evaluating to null.

In the AbstractAuthenticator, `getCurrentUser` will return the org.owasp.esapi.User.ANONYMOUS User instance if the current User reference is null at that point.  So in that context, I agree that if the application is configured to use an extension of AbstractAuthenticator, and the getCurrentUser function has not been modified, that the branch of the user being null in the ClientInfo is simply not possible.

Since it is possible to override the ESAPI.authenticator on a per-instance basis I don't think we can rely on the ANONYMOUS user reference being set through that mechanism.

With that in mind, when the ClientInfo acquires the user from ESAPI.authenticator there is a chance that the value is not set and will be null.  

In that case, are you recommending that we hard-code the username 'ANONYMOUS' to the log content?

I want to ask this specifically, since it is another slight difference in the implementation between the SLF4J Log and both the Log4J and Java implementations.

If we do want to hard-code the user name String, would we also want to hard-code the last host address?  (if yes, please let me know what that default value should be)

### (UPDATED) For the client portion of the message:  
   `USER_ACCOUNT_NAME:SESSION_ID@REMOTE_CONNECTION_INFO`
  - If the user evaluates to null, the message is an empty string, the result would be `ANONYMOUS:@UNKNOWN_HOST`

**Comment by kwwall** [comment]
A null username indicates that the user is / has not authenticated. So
ANONYMOUS fits that fine. (Well, as long as "ANONYMOUS" isn't a valid user
name. Maybe "#ANONYMOUS#" or similar would be better.)

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by jeremiahjstacey** [comment]
Sounds good.  I will proceed to hard-code the user name to '#ANONYMOUS#' in the off case the User object is returned as null from the Authenticator.

Should I also supply the default value of '#UNKNOWN_HOST#' for the last host address in this case?

The result will either be:  `#ANONYMOUS#:@`  or `#ANONYMOUS#:@#UNKNOWN_HOST#`

**Comment by kwwall** [comment]
Yes. Let's make them consistent. We should make necessary changes so that
the JUL and log4j implementations do the same as well, although that can be
done in a separate PR if you want.

>

**Comment by jeremiahjstacey** [comment]
I was hoping you'd suggest that.  Making the following changes to both the Java and Log4J implementation should enforce consistency.

If we move forward with this, then this may cause merge conflicts with the #529 content.
- when these are merged together, please note that the first boolean argument to the LogPrefixAppender will allow the user information to be toggled off. 

I have made these changes locally and all unit tests are passing.  I have not created new unit tests for this update to either instance at this point.


[commonLoggerPrefix-PATCH.txt](https://github.com/ESAPI/esapi-java-legacy/files/3935419/commonLoggerPrefix-PATCH.txt)

### Log4JLogger.log Content (ORIGINAL)
```
		// ensure no CRLF injection into logs for forging records
		String clean = message.replace('\n', '_').replace('\r', '_');
		if (ESAPI.securityConfiguration().getLogEncodingRequired()) {
			clean = ESAPI.encoder().encodeForHTML(message);
			if (!message.equals(clean)) {
				clean += " (Encoded)";
			}
		}

		// log server, port, app name, module name -- server:80/app/module
		StringBuilder appInfo = new StringBuilder();
		if (ESAPI.currentRequest() != null && logServerIP) {
			appInfo.append(ESAPI.currentRequest().getLocalAddr()).append(":").append(ESAPI.currentRequest().getLocalPort());
		}
		if (logAppName) {
			appInfo.append("/").append(applicationName);
		}
		appInfo.append("/").append(getName());

		//get the type text if it exists
		String typeInfo = "";
		if (type != null) {
			typeInfo += type + " ";
		}

		// log the message
		// Fix for https://code.google.com/p/owasp-esapi-java/issues/detail?id=268
		// need to pass callerFQCN so the log is not generated as if it were always generated from this wrapper class
		log(Log4JLogger.class.getName(), level, "[" + typeInfo + getUserInfo() + " -> " + appInfo + "] " + clean, throwable);
	}
```
### Log4JLogger.log content(UPDATED)
```
		LogPrefixAppender prefixAppender = new LogPrefixAppender(true, logServerIP, logAppName, applicationName);
		String fullLogMsg = prefixAppender.appendTo(getName(), type, message);

		// ensure no CRLF injection into logs for forging records
		String clean = fullLogMsg.replace('\n', '_').replace('\r', '_');
		if (ESAPI.securityConfiguration().getLogEncodingRequired()) {
			clean = ESAPI.encoder().encodeForHTML(message);
			if (!fullLogMsg.equals(clean)) {
				clean += " (Encoded)";
			}
		}

		// log the message
		// Fix for https://code.google.com/p/owasp-esapi-java/issues/detail?id=268
		// need to pass callerFQCN so the log is not generated as if it were always generated from this wrapper class
		log(Log4JLogger.class.getName(), level, clean, throwable);
	}
```

### JavaLogFactory.log Content (ORIGINAL)
```
  String clean = message.replace( '\n', '_' ).replace( '\r', '_' );
            if ( ESAPI.securityConfiguration().getLogEncodingRequired() ) {
            	clean = ESAPI.encoder().encodeForHTML(message);
                if (!message.equals(clean)) {
                    clean += " (Encoded)";
                }
            }

			// log server, port, app name, module name -- server:80/app/module
			StringBuilder appInfo = new StringBuilder();
			if ( ESAPI.currentRequest() != null && logServerIP ) {
				appInfo.append( ESAPI.currentRequest().getLocalAddr() + ":" + ESAPI.currentRequest().getLocalPort() );
			}
			if ( logAppName ) {
				appInfo.append( "/" + applicationName );
			}
			appInfo.append( "/"  + moduleName );
			
			//get the type text if it exists
			String typeInfo = "";
			if (type != null) {
				typeInfo += type + " ";
			}
			
			// log the message
			jlogger.log(level, "[" + typeInfo + getUserInfo() + " -> " + appInfo + "] " + clean, throwable);
```

### JavaLogFactory.log Content (UPDATED)
```
  LogPrefixAppender prefixAppender = new LogPrefixAppender(true, logServerIP, logAppName, applicationName);
            String fullLogMsg = prefixAppender.appendTo(moduleName, type, message);
            
            // ensure no CRLF injection into logs for forging records
            String clean = fullLogMsg.replace( '\n', '_' ).replace( '\r', '_' );
            if ( ESAPI.securityConfiguration().getLogEncodingRequired() ) {
            	clean = ESAPI.encoder().encodeForHTML(message);
                if (!fullLogMsg.equals(clean)) {
                    clean += " (Encoded)";
                }
            }

			// log the message
			jlogger.log(level, clean, throwable);
```

**Comment by jeremiahjstacey** [comment]
Looking a little closer, I think I would prefer to address the Log4J and Java instances in a separate effort.

**Comment by kwwall** [comment]
I thought you might which is why I suggested the separate PR.

**Comment by jeremiahjstacey** [comment]
PR has been merged

**Comment by jeremiahjstacey** [comment]
PR has been approved, has not been merged yet.  Jumped the gun. :)
