### ISSUE TITLE
Create release notes for 2.2.1.1 patch release

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#564]
Document the release notes in documentation/esapi4java-core-2.2.1.1-release-notes.txt

**Comment by davewichers** [comment]
Looks like this was done in commit 156b98cd8aaa7a21d483bded315f3509663576b2

**Comment by jeremiahjstacey** [comment]
Work has been completed in commit https://github.com/ESAPI/esapi-java-legacy/commit/156b98cd8aaa7a21d483bded315f3509663576b2, as noted above.
