### ISSUE TITLE
API doc comments are not shown when using ESAPI in Intellij Idea

### ISSUE THREAD

**Issue by cdwijayarathna** [ESAPI/esapi-java-legacy#566]
I am using esapi-2.2.1.0.jar that I downloaded from https://mvnrepository.com/artifact/org.owasp.esapi/esapi .

When I applied this jar to my JSP web application, I don't see any API doc comments in the IDE cues. Furthermore, the method parameter names are shown as "String s" rather than with their descriptive names.

I can already see that the pom.xml uses [attach-javadocs and attach-sources plugins](https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html).

![image](https://user-images.githubusercontent.com/1338607/88620115-d4bef400-d0ba-11ea-85d7-387fb70dba2d.png)

![image](https://user-images.githubusercontent.com/1338607/88620206-0cc63700-d0bb-11ea-90ba-2ea2002b35ea.png)

![image](https://user-images.githubusercontent.com/1338607/88620269-2d8e8c80-d0bb-11ea-9fc0-d24cba6f0899.png)

![image](https://user-images.githubusercontent.com/1338607/88620315-4e56e200-d0bb-11ea-9dc6-eec16c03f404.png)

**Comment by kwwall** [comment]
@cdwijayarathna - Okay, I can see this is not working. Could I get you to reference a FOSS library that is using Maven where it _is_ working so I can have a working model to compare to ESAPI? Thanks.

**Comment by cdwijayarathna** [comment]
@kwwall This happened when I added the jar file manually to my project. Now I tried adding it as a Gradle dependency and I could see the doc comments and parameter names. I believe this would be the case if I used maven as well. I attempted importing several FOSS libraries manually to a project as I did previously and none of them showed me doc comments so far. 

However, most of them showed me self explaining parameter names (i.e. 'String pattern' not 'String s'), compared to ESAPI (e.g. https://github.com/google/gson).

Should we ignore this then? What do you think?

**Comment by kwwall** [comment]
Let me test it tomorrow and get back to you. I generally only resort to
using an IDE if I need to use a debugger or if I am working with unfamiliar
code, so I've not done that with ESAPI for quite some time. (I usually just
use gvim and a *nix shell to develop code.) But I'm sure I have a simple
ESAPI "Hello World" program lying around somewhere that I can test this out
on both with and without being configured as a Maven project.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by kwwall** [comment]
Yeah, I'm going to close this out. If I import something as a "Maven" project in Eclipse, everything works. So there must be some behind the scenes magic that the IDEs are doing when they see that it is a Maven or Gradle build. Here's proof that it's working:
![image](https://user-images.githubusercontent.com/1959835/88881582-c75e5280-d1fd-11ea-8220-c7f001ac473b.png)


So I'm going to close this.
