### ISSUE TITLE
Logger.always() fails to log all the time when ESAPI is using org.owasp.esapi.logging.java.JavaLogFactory

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#571]
Tested in ESAPI 2.2.1.1

The _intent_ of the two `Logger.always()` methods is to _always_ do logging regardless of what the log level is set to in your logging configuration. However, if ESAPI is using the (current) default JUL as logging via setting

`ESAPI.Logger=org.owasp.esapi.logging.java.JavaLogFactory`

in **ESAPI.properties** and in **esapi-java-logging.properties**, the log level is set to 'INFO', then this will not produce any output:

`        ESAPI.log().always(Logger.EVENT_SUCCESS,"This should ALWAYS appear!!!");`

However, changing the entry
`java.util.logging.ConsoleHandler.level = INFO`
to
`java.util.logging.ConsoleHandler.level = ALL`

will cause the Logger.always() output to correctly log.

**Comment by kwwall** [comment]
@jeremiahjstacey - If you have some time, could you take a quick look at this? If you don't have time to fix it and submit a PR, then maybe just point me to the proper place to fix it and outline what needs to be done? Thanks.

**Comment by jeremiahjstacey** [comment]
I'm debugging the method that you've outlined above and I think I have found the root of the issue.  I believe that the underlying Java Logger is filtering out java.util.Level.ALL by default. 

As the code exists now:
- The ESAPI Level.ALL maps to the java.util.Level.ALL
- ESAPI Logger.always does always propagate the log event to the delegate Logger.
- The Java Logger implementation defaults to INFO.  The implementation of java.util.Logger.isLoggable filters out Level.ALL when set to Level.INFO

In the source I have for Java, the java.util.Logging.isLoggable method is as follows:
```
  /**
     * Check if a message of the given level would actually be logged
     * by this logger.  This check is based on the Loggers effective level,
     * which may be inherited from its parent.
     *
     * @param   level   a message logging level
     * @return  true if the given message level is currently being logged.
     */
    public boolean isLoggable(Level level) {
        if (level.intValue() < levelValue || levelValue == offValue) {
            return false;
        }
        return true;
    }
```
Note the first part of the if block which compares the int values of the java.util.Logging Level against the current system configuration.   The int values are determined by the java.util.Level Enumeration:
```
public static final Level INFO = new Level("INFO", 800, defaultBundle);
public static final Level ALL = new Level("ALL", Integer.MIN_VALUE, defaultBundle);
```
The explicit value of Integer.MIN_VALUE is -2147483648

Here is the call stack for this execution:
```
Thread [main] (Suspended)	
	Logger.isLoggable(Level) line: 1721	
	JavaLogLevelHandlers.isEnabled(Logger) line: 40	
	JavaLogBridgeImpl.log(Logger, int, Logger$EventType, String) line: 55	
	JavaLogger.log(int, Logger$EventType, String) line: 43	
	JavaLogger.always(Logger$EventType, String) line: 61	
```

Given this information, I believe the following statement is currently true:
> ESAPI Logger.always will always propagate logging information to the delegate Logging implementation at the designated level.  The underlying Logger implementation is required to be configured to support the associated level for the output to be viewed.

----

I guess I misunderstood what the Java Level.ALL documentation actually meant:
https://docs.oracle.com/javase/7/docs/api/java/util/logging/class-use/Level.html
>Level.ALL
>ALL indicates that all messages should be logged.

Although both **OFF** and  **ALL** are a valid Java Logging Levels, I believe that they are intended to only be used by the Logging configuration.

I propose the following process to resolve this issue:

(1) Rename the `ESAPIErrorJavaLevel` class to `ESAPICustomJavaLevels` and add another entry that can account for what we actually intend as Always. 

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/java/ESAPIErrorJavaLevel.java

```
    /**
     * Defines a custom level that should result in content always being recorded, unless the Java Logging configuration is set to OFF.
     */
    public static final Level ALWAYS_LEVEL = new ESAPICustomJavaLevel( "ERROR", Level.OFF.intValue() - 1);

```

(2) Add the mapping associations in the `JavaLogLevelHandlers` to make the ALWAYS association availble
https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/java/JavaLogLevelHandlers.java
```
// ALL(Level.ALL), //DELETE THIS -- not a valid level for a Log event.
ALWAYS(ESAPICustomJavaLevel.ALWAYS_LEVEL ),
```
(3) Update the static map in the JavaLogFactory  to map ESAPI Logger.ALL to the ALWAYS logging behavior:

https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/logging/java/JavaLogFactory.java
```
        Map<Integer, JavaLogLevelHandler> levelLookup = new HashMap<>();
        levelLookup.put(Logger.ALL, JavaLogLevelHandlers.ALWAYS); 
```
---

I believe that this should address the underlying issue.   There will probably need to be test updates to account for the variation in the configuration, I did not look very far into that.

**Comment by jeremiahjstacey** [comment]
PR 572 adds the implementation content above.  I did add one additional test for the adjustment to the JavaLogHandler.
All tests passed from my local executions, so I think that should be good to merge if that is an acceptable solution.

If an alternative implementation would be desired, please let me know and I will do my best to re-assess and address or provide recommendations.

**Comment by kwwall** [comment]
Close via merge of PR #572 and commit e0943e2.
