### ISSUE TITLE
Separate Crypto Related Properties into Separate File

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#58]
_From [neil.mat...@gmail.com](https://code.google.com/u/113193370122541371183/) on November 06, 2009 14:56:02_

It has been requested that the crypto properties be kept in a different
file for more separation and fine grained control of information.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=48_

**Comment by kwwall** [comment]
Fixed as part of more general feature enhancements addressed in issue #350. Can be addressed by placing ESAPI crypto properties into a separate properties file controlled by the operations team and not checked into your SCM. For further details, see "documentation/ESAPI-configuration-user-guide.md".
