### ISSUE TITLE
Not able to turn off Java.util.Logging for ESAPI

### ISSUE THREAD

**Issue by arpita012020** [ESAPI/esapi-java-legacy#592]
I am not able to turn off Java.util.Logging for ESAPI. The properties in esapi-java-logging.properties is not being loaded when application is egtting started. Please help.

**Comment by xeno6696** [comment]
This is vague.  

Please follow traditional troubleshooting etiquette:

1.  Expected Outcome
2. Outcome that differs from expectations
3. What steps have you performed to get this far
4. Provide a simple unit-test that faithfully replicates the problem
5. Any logging/stacktrace information recovered 

Please ensure you've read the [release notes.](https://github.com/ESAPI/esapi-java-legacy/releases/esapi-2.2.1.1) and the attendant discussion at #560

**Comment by xeno6696** [comment]
Cannot reproduce.

**Comment by arpita012020** [comment]
My expectation is ESAPI will validate our request parameter . but should not print any log since some of my request parameters are PII data and I don't want it to be logged.
We are using JavaLogFactory for logging. Also made following change in esapi-java-logging.properties:
**handlers= java.util.logging.ConsoleHandler
.level= OFF
java.util.logging.ConsoleHandler.level = OFF
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=[%1$tF %1$tT] [%3$-7s] %5$s %n
#https://www.logicbig.com/tutorials/core-java-tutorial/logging/customizing-default-format.html**

But still it is printing logs since esapi-java-logging.properties file not being loaded at all. 

We also tried commenting ESAPI.Logger in ESAPI.properties file. But it is taking JavaLogFactory  as default logger.

Please help.

**Comment by xeno6696** [comment]
@jeremiahjstacey I'm going to invoke you... I haven't set up an ESAPI logger since the updates.

**Comment by kwwall** [comment]
@jeremiahjstacey  -- forgot this and look at GitHub issue #594. @arpita012020 opened a new ticket there (same as this one) because this one was closed.
