### ISSUE TITLE
Move HTMLValidationRule static Classpath handling into DefaultSecurityConfiguration

### ISSUE THREAD

**Issue by jeremiahjstacey** [ESAPI/esapi-java-legacy#608]
To ensure more consistency with implementations, the  multi-classloading behavior should be moved into the DefaultSecurityConfiguration so that all instances act the same.

This task is being created as a follow-on of Issue #310, and the work done for ensuing HTMLValidationRuleClasspathTest is consistent - PR #607

**Comment by kwwall** [comment]
Closed via PR #607.
