### ISSUE TITLE
Add Deprecation Logging content for Log4JLogFactory Usage

### ISSUE THREAD

**Issue by jeremiahjstacey** [ESAPI/esapi-java-legacy#610]
Add warning-level logging to the Log4JLogFactory to increase visualization of the deprecation status.

Upon construction of a new Log4JLogFactory, a warning message will be logged to declare intent of deprecation.

`.warning("DEPRECATION - ESAPI Support for Log4JLogFactory/Logger will be removed in a future release.")`

**Comment by xeno6696** [comment]
So when the Log4JFactory creates a new instance?  That's perfect.  One statement right on instantiation.

**Comment by jeremiahjstacey** [comment]
@xeno6696, sounds simple enough.

Preferred method to use the LogFactory to generate the log message to keep format consistent. 
  - **Deprecation** warning would be appropriate to classify as a SECURITY_AUDIT?
  - May need to mark the getLogger methods final to prevent scanners from detecting the call of an overridable method from a constructor.
```
/** Default Constructor. */
    public Log4JLogFactory() {
        Logger logger = getLogger(Log4JLogFactory.class);
        logger.warning(Logger.SECURITY_AUDIT, "DEPRECATION - ESAPI Support for Log4JLogFactory/Logger will be removed in a future release.");
    }
```

**Comment by kwwall** [comment]
Yes, this makes sense to me. I only wonder if the message should state **_when_** that removal may take place. If we keep with our stated deprecation policy (which I prefer to do), we had to wait 2 years after the release we first announced it, which would make it no sooner than 2022-07-23.

I see pros and cons of doing this. Pro: Developers will know how long then have to plan to make the switch. Cons: Humans procrastinate so maybe it's better not to tell them.

Which do you think is the best approach? I don't have strong feelings either way.

**Comment by jeremiahjstacey** [comment]
`"DEPRECATION (2022-07-23)   ESAPI Support for Log4J will be eligible for removal 2 years from initial notification."`

We can't control the human factor.  We can only provide information.  Makes it easier to not be sympathetic when someone realizes it just "stops working" at the end of the deadline.

**Comment by kwwall** [comment]
@jeremiahjstacey - I think that wording will be confusing, especially to those for whom English is a second language because then not associate that date with the end of the 2 year period. How about:
```
        logger.warning(Logger.SECURITY_AUDIT, "DEPRECATION - ESAPI Support for Log4JLogFactory/Logger will be removed shortly after 2022-07-23, which is 2 years after the initial notification.");
```

**Comment by jeremiahjstacey** [comment]
@kwwall @xeno6696  Going to be working on this one next.

I was thinking that having some additional documentation on the deprecation content might be helpful?
* Add a "Deprecations" tab to the existing content - https://owasp.org/www-project-enterprise-security-api/
  * Use a three column table: 
|API/Feature | Notification Date | Deprecation Date|
|Log4J | 2020-07-23 |2022-07-23 | 
|Java7  | date | date |
  * Maybe update the Wiki link here to point at the new documentation
    * https://github.com/ESAPI/esapi-java-legacy/wiki

Downside is the maintenance of something like that.  Not sure if it's worth it?

**Comment by jeremiahjstacey** [comment]
Looking for input @kwwall @xeno6696 

Turns out, this is going to be a little more difficult than anticipated.  When the logging event attempts to add the client info the FileBasedAuthenticator is initialized.  During that initialization, we try to grab the currently constructed LogFactory -- which isn't constructed, so another is constructed.  The constructor calls the logger, which tries to get the client info, and we are in an infinite loop.

The easiest way to work around this is to just call a log4j logger directly, and bypass the additional context that ESAPI provides (client info, server info, etc), as well as skipping the encoding and the newline protection.  Given the limited scope of where this is to be applied, I don't see a large risk in this implementation.

```
 /** Default Constructor. */
    public Log4JLogFactory() {
        org.apache.log4j.Logger log4JLogger = org.apache.log4j.Logger.getLogger(Log4JLogFactory.class);
        log4JLogger.log(org.apache.log4j.Level.WARN, "DEPRECATION - ESAPI Support for Log4JLogFactory/Logger will be removed shortly after 2022-07-23, which is 2 years after the initial notification.");
    }
```

If the additional info or the logging guards are required I will try to negotiate another option.

**Comment by xeno6696** [comment]
Well, IIRC when we haven't instantiated a logger elsewhere we print to console out.  While that is usually frowned upon and we could question it here, wouldn't that be at least sticking to convention?

**Comment by jeremiahjstacey** [comment]
Would we want to reuse the existing public static method?
`DefaultSecurityConfiguration.logToStdout(String, Throwable)`

**Comment by kwwall** [comment]
@jeremiahjstacey  - Just a few things to consider. There are pros and cons of using `DefaultSecurityConfiguration.logToStdout(String, Throwable)`. The pro is that is is really trivial. The cons are that 1) it wouldn't be formatted like the rest of the logs, 2) it won't end up in the same log file as the rest of the ESAPI SECURITY_AUDIT logs and thus may get missed, and 3) if the application has set the `System` property **org.owasp.esapi.logSpecial.discard** to `true`, the log output would just get discarded. (I often run JUnit tests with that set to true as it removes a lot of the clutter and given that someone complained about all the logSpecial() output in the first place, there may be a lot of developers who also do that with there applications.) 

However, regardless of what implementation approach that you take, I do agree that it would be a good idea to add a 'Deprecated' tab to the OWASP ESAPI wiki page. That is under https://github.com/OWASP/www-project-enterprise-security-api which I think you are listed as an 'Outside Collaborator' and thus I think you have commit access. (If not, I guess you could fork it and do a PR.) Futzing with the tabs to create a new one is a bit tricky. You should just be able to follow the pattern of (say) 'tab_shouldiuseesapi.md'. I do recall it has to start with 'tab_' and be a MarkDown file with a '.md' suffix. If you decide to do that, please open a new instance in that GitHub repo so they can track it and then be sure to reference the ESAPI issue. You would set 'order: 7' in the initial section unless there was some reason that you think it should appear earlier, in which case we have to re-order all of the others. Hope that helps a bit.

**Comment by jeremiahjstacey** [comment]
log4JLogFactory is removed as of v.2.5.0.0.   This work is no longer a concern
