### ISSUE TITLE
java.io.FileNotFoundException Error in Logs When ESAPI.properties and validation.properties are in resources.

### ISSUE THREAD

**Issue by McDeCoderDude** [ESAPI/esapi-java-legacy#653]
We are receiving  java.io.FileNotFoundException when we have the property files in the resources directory which will be on runtime classpath. Application runs as excepted as property files are loaded. Just looking for a way to not get this error message during startup of our application.  esapi version 2.2.3.1.

**Comment by kwwall** [comment]
@McDeCoderDude - Could you include a full exception stack trace to help us diagnose this?  If there is anything sensitive / proprietary in the stack trace, you can just edit it out with something like '<redacted>' or whatever.

**Comment by McDeCoderDude** [comment]
Here is part of output from log file. The Exception was: java.io.FileNotFoundException triggers some detection tools we are running just wonder if there was a way to quiet that in logs. As it files are found and loaded.

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
ESAPI: WARNING: System property [org.owasp.esapi.opsteam] is not set
ESAPI: WARNING: System property [org.owasp.esapi.devteam] is not set
ESAPI: Attempting to load ESAPI.properties via file I/O.
ESAPI: Attempting to load ESAPI.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: /home/ubuntu/scheduler/ESAPI.properties
ESAPI: Not found in SystemResource Directory/resourceDirectory: .esapi/ESAPI.properties
ESAPI: Not found in 'user.home' (/home/ubuntu) directory: /home/ubuntu/esapi/ESAPI.properties
ESAPI: Loading ESAPI.properties via file I/O failed. Exception was: java.io.FileNotFoundException
ESAPI: Attempting to load ESAPI.properties via the classpath.
ESAPI: SUCCESSFULLY LOADED ESAPI.properties via the CLASSPATH from '/ (root)' using current thread context class loader!        
ESAPI: SecurityConfiguration for Validator.ConfigurationFile.MultiValued not found in ESAPI.properties. Using default: false    
ESAPI: Attempting to load validation.properties via file I/O.
ESAPI: Attempting to load validation.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: /home/ubuntu/scheduler/validation.properties    
ESAPI: Not found in SystemResource Directory/resourceDirectory: .esapi/validation.properties
ESAPI: Not found in 'user.home' (/home/ubuntu) directory: /home/ubuntu/esapi/validation.properties
ESAPI: Loading validation.properties via file I/O failed.
ESAPI: Attempting to load validation.properties via the classpath.
ESAPI: SUCCESSFULLY LOADED validation.properties via the CLASSPATH from '/ (root)' using current thread context class loader!

**Comment by kwwall** [comment]
Yeah, you can get rid of those messages by running it as:
`java -Dorg.owasp.esapi.logSpecial.discard=true ...`

So, this is not a bug, but a feature. See https://javadoc.io/doc/org.owasp.esapi/esapi/latest/org/owasp/esapi/reference/DefaultSecurityConfiguration.html for details of how ESAPI searches for the **ESAPI.properties** file.
