### ISSUE TITLE
JavaEncryptor.java HARDCODED_CREDENTIALS 

### ISSUE THREAD

**Issue by JerryDevis** [ESAPI/esapi-java-legacy#669]
Encryptor.MasterKey=a6H9is3hEVGKB4Jut+lOVA==
Encryptor.MasterSalt=SbftnvmEWD5ZHHP+pX3fqugNysc=

The value PublicKey/PrivateKey needs to be transferred through input parameters.

**Comment by xeno6696** [comment]
@JerryDevis 

Where are you seeing this?  

![image](https://user-images.githubusercontent.com/9502785/158930310-218e19a5-0c51-4d49-bb8e-cb14cca2d814.png)


^^^This is not hardcoded.

**Comment by xeno6696** [comment]
In the default configuration file packaged with the library, we have this:

![image](https://user-images.githubusercontent.com/9502785/158930550-5a567ebf-38c5-425c-9768-cefc475085a6.png)

**Comment by xeno6696** [comment]
Confirmed.  The reference key discussed by @JerryDevis applies to the one in `src/test/resources/esapi/ESAPI.properties` on line 171.  

So, it IS the properties `Encryptor.MasterKey` and `Encryptor.MasterSalt` that serves as the user-generated input values.  If the key `a6H9is3hEVGKB4Jut+lOVA==` is in your server environment, then it means that you likely (you, as in, the web audience) copied test properties into production and likely never had a security review.  

I'm going to close this.  The password isn't hardcoded, and `ESAPI.properties` IS an input source.

**Comment by kwwall** [comment]
The one under src/test/resources/esapi/ESAPI.properties has hard code TEST
values for these 2 properties,  but
1) that is by intention as we need it for testing, and
2) there is a prominent warning at the beginning of the file that warns not
to base your production ESAPI.properties file on it.

The same values and warning are likely in other versions of that file under
src/test/resources/esapi as well, and the same applies there.

If people ignore the warnings,  there's not much we can do. So I agree with
@xeno6696 that this should be closed as not an issue.

-kevin
