### ISSUE TITLE
ESAPI canonicalization in DefaultEncoder ignoring Encoder.DefaultCodecList property

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#686]
In the **ESAPI.properties** file, there is this comment and property name / value:
```
# The default list of codecs to apply when canonicalizing untrusted data. The list should include the codecs
# for all downstream interpreters or decoders. For example, if the data is likely to end up in a URL, HTML, or
# inside JavaScript, then the list of codecs below is appropriate. The order of the list is not terribly important.
Encoder.DefaultCodecList=HTMLEntityCodec,PercentCodec,JavaScriptCodec
```
However, contrary to the comment here, this property seems to be getting ignored by the private default CTOR for `DefaultEncoder` and the `HTMLEntityCodec`, `PercentCodec`, and `JavaScriptCodec` are loaded in that order via being hard-coded. However, there is a 2nd public CTOR that takes a `List<String>` representing available (or customized) codecs that could be used with this property. (Question: When is a singleton not a singleton? Answer: When someone uses the other public CTOR. Poor design, but fortunately not any mutable instance variables.)

So, obviously a developer use the ESAPI property with the public CTOR using something like:

```
import org.owasp.esapi.Encoder;
import org.owasp.esapi.reference.DefaultEncoder;

    ...
    Encoder enc =  DefaultEncoder( ESAPI.securityConfiguration().getDefaultCanoicalizationCodecs() );

    String canonicalized = enc.canonicalize( input );
    ...
```

But I don't think that is what was implied by the comment in ESAPI.properties, nor do I think that we want to encourage the direct invocation of a CTOR in a reference implementation class that was intended to be a singleton instance in the first place. So many things wrong with that.

**Comment by kwwall** [comment]
@xeno6696 and @jeremiahjstacey -- would appreciate your eyeballs on this. I thought that maybe this was discussed once before but I can't find any record that it has been reported. Maybe we looked at it and decided it wasn't a bug.

That said, if it is a bug, one option would to just be to remove the property I guess or deprecate it in case someone is using it in the way described above.

**Comment by xeno6696** [comment]
Yeah, this tickles my memory from back in '17.  One of us noted that this was getting ignored, but for sure we didn't generate an issue for it, and knowing how I think I likely figured that there were bigger fish to fry.  At that time of course.  I'll do some deep searching tomorrow.

**Comment by planetlevel** [comment]
Not sure the right design here exactly, but there are good reasons to have multiple  Encoders with different codec stacks.  You should choose the codecs based on the upstream systems that you're getting data from and the downstream systems you're sending data to.   That might be different for different parts of a single app.... so having a single singleton isn't right.   Of course, nor is ignoring the property intended to configure the default.
