### ISSUE TITLE
Plugin/Dependency Version Updates

### ISSUE THREAD

**Issue by jeremiahjstacey** [ESAPI/esapi-java-legacy#690]
`mvn versions:display-plugin-updates`
`mvn versions:display-dependency-updates`

Run both commands.  Ensure that all recommended versions are valid releases and apply recommended updates.

If any versions are not valid releases, file a new issue to update the version ruleset file to account.

Verification:
1. `mvn clean package` must succeed
2. `mvn site:site` must succeed

If any versions cannot be updated file new issues for visibility.

**Comment by jeremiahjstacey** [comment]
```
$ mvn versions:display-plugin-updates
[INFO] Scanning for projects...
[WARNING] Failed to retrieve plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0: Failed to parse plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0 (C:\Users\Jeremiah\.m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.12.0\findsecbugs-plugin-1.12.0.jar): No plugin descriptor found at META-INF/maven/plugin.xml
[INFO]
[INFO] -----------------------< org.owasp.esapi:esapi >------------------------
[INFO] Building ESAPI 2.4.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Failed to retrieve plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0: Failed to parse plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0 (C:\Users\Jeremiah\.m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.12.0\findsecbugs-plugin-1.12.0.jar): No plugin descriptor found at META-INF/maven/plugin.xml
[INFO]
[INFO] --- versions-maven-plugin:2.10.0:display-plugin-updates (default-cli) @ esapi ---
[INFO]
[INFO] The following plugin updates are available:
[INFO]   maven-project-info-reports-plugin .................. 3.2.2 -> 3.3.0
[INFO]   maven-site-plugin .............................. 3.12.0 -> 4.0.0-M1
```

```
$ mvn versions:display-dependency-updates
[INFO] Scanning for projects...
[WARNING] Failed to retrieve plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0: Failed to parse plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0 (C:\Users\Jeremiah\.m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.12.0\findsecbugs-plugin-1.12.0.jar): No plugin descriptor found at META-INF/maven/plugin.xml
[INFO]
[INFO] -----------------------< org.owasp.esapi:esapi >------------------------
[INFO] Building ESAPI 2.4.1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Failed to retrieve plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0: Failed to parse plugin descriptor for com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0 (C:\Users\Jeremiah\.m2\repository\com\h3xstream\findsecbugs\findsecbugs-plugin\1.12.0\findsecbugs-plugin-1.12.0.jar): No plugin descriptor found at META-INF/maven/plugin.xml
[INFO]
[INFO] --- versions-maven-plugin:2.10.0:display-dependency-updates (default-cli) @ esapi ---
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   com.github.spotbugs:spotbugs-annotations .............. 4.6.0 -> 4.7.0
[INFO]
[INFO] The following dependencies in Plugin Dependencies have newer versions:
[INFO]   com.github.spotbugs:spotbugs .......................... 4.6.0 -> 4.7.0
```

**Comment by kwwall** [comment]
@jeremiahjstacey - If I'm not mistaken, I already suggest running both of those in the "ESAPI Release Steps" document. But perhaps we should mention in it the "CONTRIBUTING-TO-ESAPI.txt" document so contributors will do it, or re-examine our Dependabot settings, as I think it can help us keep Maven plugins up-to-date as well. (I think AntiSamy does this already.) Thoughts?

**Comment by jeremiahjstacey** [comment]
I was going to pose that question in the PR for these updates.

If we plan on keeping up to date, I think that doing it at the release is not frequent enough.  We're pretty much guaranteed to hit a conflict at some point, and there's no runway to address it if we only do it there.

If dependabot can handle it, then that may be better.  I was not sure of the frequency that runs.

tbh, I also wanted to verify that the version exclusion file is working the way I was expecting.  It seems to work so far, but I'm waiting for that edge-case that I've missed.

**Comment by kwwall** [comment]
I think the frequency can be tweaked. If you do it from a workflow, you can even doing it as part of a PR. But I think it is presently set up to run weekly. Feel free to adjust it; I think you should have permissions.

**Comment by jeremiahjstacey** [comment]
Thanks for pointing that out.  I'll poke around in the project config and see if I can find where that's all set up!
