### ISSUE TITLE
Improve ConfigurationException message thrown from EsapiPropertyLoaderFactory.createPropertyLoader()

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#735]
If the passed in configuration file name has neither a suffix of ".properties" or ".xml", then this is thrown:
```java
throw new ConfigurationException("Configuration storage type [" + fileExtension + "] is not " +
                    "supported");
```

This exception message does not clearly convey what is expected for the ESAPI client to do to make it work.

**Describe the solution you'd like**
Replace the current code, shown above, with something similar to this:
```java
throw new ConfigurationException("Configuration path of [" + cfgPath + "] has unsupported file suffix." +
                    "Only .properties or .xml file suffix is supported.");
```

**Comment by HenriquePinto333** [comment]
I'll take a peek on this. I'll think of an appealing and intuitive message in order for everyone to understand what type of files shoud be supported.

**Comment by kwwall** [comment]
@HenriquePinto333 - Thanks. That would be great. If this is your first time contributing to ESAPI, be sure to read https://github.com/ESAPI/esapi-java-legacy#contributing-to-esapi-legacy.

Also, for a bit of context, you may want to read through the posts at https://groups.google.com/a/owasp.org/g/esapi-project-users/c/k9335ATXcoE on the ESAPI Project Users mailing list. (You should be able to read it even if you are not subscribed to the list.)
