### ISSUE TITLE
ESAPI 2.5.1.0 not working with spring boot 3.0, spring 6

### ISSUE THREAD

**Issue by dwhacker** [ESAPI/esapi-java-legacy#769]
When using latest version of ESAPI 2.5.1.0, it gives classNotFound for javax.servlet.
As we know Spring boot 3.0 uses jakarta.servlet.
Will it be fixed in upcoming releases?

**Comment by kwwall** [comment]
See discussion at:
https://github.com/ESAPI/esapi-java-legacy/discussions/768

**Comment by xeno6696** [comment]
Closing issue as the discussion is already well underway.
