### ISSUE TITLE
Add documenttion to CONTRIBUTING-TO-ESAPI.txt to mention signed commits are now required.

### ISSUE THREAD

**Issue by kwwall** [ESAPI/esapi-java-legacy#775]
_Master_ and _develop_ branches now have "branch protection" enabled and as part of that, those branches now require signed commits. That should be mentioned as part of the PR process in the **CONTRIBUTING-TO-ESAPI.txt** file.

While we can bypass this via GitHub, it is better if all the commits are signed with GPG keys.

**Comment by Koslx888** [comment]
Master and develop

**Comment by kwwall** [comment]
It has been in the 'develop' branch for a while now:
https://github.com/ESAPI/esapi-java-legacy/blob/develop/CONTRIBUTING-TO-ESAPI.txt#L15-L22

It has been merged to 'main' since the 2.5.2.0 release which was about 3 months ago:
https://github.com/ESAPI/esapi-java-legacy/blame/main/CONTRIBUTING-TO-ESAPI.txt#L15-L22

The only problem was that I failed to close this issue, which I am doing now.
