### ISSUE TITLE
хз

### ISSUE THREAD

**Issue by Koslx888** [ESAPI/esapi-java-legacy#792]
# NOTE: Ware aware the problems with ESAPI and Jakarta EE, so please do NOT create a new issue for that.
To follow the status of that, please see GitHub Discussion https://github.com/ESAPI/esapi-java-legacy/discussions/768.

**Describe the bug**

**Specify what ESAPI version(s) you are experiencing this bug in**
This is especially important if it is not the latest version of ESAPI.

**To Reproduce**
List the steps to reproduce the behavior or (ideally) attach a small JUnit test to reproduce the problem. Please _be specific_.

**Expected behavior**

**Screenshots**
[**NOTE:** Please do NOT just ask general questions here as they will _not_ be answered. Instead, please use the GitHub Discussions and create a new topic under 'Questions and Answers".
Please delete any irrelevant portion of this template before submitting your GitHub issue. Thanks.]

**Platform environment (please complete the following information):**
 - JDK version used with ESAPI

**Additional context**
If known, please select the label corresponding to the affected ESAPI component.

**Comment by kwwall** [comment]
Other than showing that I made a typo in the NOTE in the GitHub issues template ('Ware' rather than 'We are'), this issue shows nothing. It is just the template itself so there is nothing to address here.
