### ISSUE TITLE
easpi .properties and validation properties are present but still it  is throwing error  and  the application is failing do you have any solution for this

### ISSUE THREAD

**Issue by sh26masood** [ESAPI/esapi-java-legacy#832]
Yeah, you can get rid of those messages by running it as:
`java -Dorg.owasp.esapi.logSpecial.discard=true ...`

So, this is not a bug, but a feature. See https://javadoc.io/doc/org.owasp.esapi/esapi/latest/org/owasp/esapi/reference/DefaultSecurityConfiguration.html for details of how ESAPI searches for the **ESAPI.properties** file.

_Originally posted by @kwwall in https://github.com/ESAPI/esapi-java-legacy/issues/653#issuecomment-1016995464_

**Comment by xeno6696** [comment]
Closing as this isn't a bug.

**Comment by kwwall** [comment]
See https://github.com/ESAPI/esapi-java-legacy/issues/831#issuecomment-1961515828 for additional details related to this.
