### ISSUE TITLE
Fix Typos

### ISSUE THREAD

**Issue by DarioViva42** [ESAPI/esapi-java-legacy#851]
This is the first Issue requested in the following comment.
https://github.com/ESAPI/esapi-java-legacy/pull/850#issuecomment-2282343202

> One PR to only correct typos in public documentation (so .md files, comments in .properties / configuration files, and Javadoc.

> Every PR that you submit needs to have a corresponding GitHub issue created for it and the PR should reference that issue.

**Comment by kwwall** [comment]
Closed via PR #852
