### ISSUE TITLE
2.6.0.0 still using javax HttpServletRequest

### ISSUE THREAD

**Issue by madmax138** [ESAPI/esapi-java-legacy#863]
According to the README at https://github.com/ESAPI/esapi-java-legacy version 2.6.0.0 should have support for Jakarta. However, we are still seeing the javax.servlet.http.HttpServletRequest in the DefaultValidator class. This breaks our app since we moved to the jakarta servlet api and no longer have the javax servlet on our classpath for tomcat 10 upgrade.

**Comment by madmax138** [comment]
This is also present in the org.owasp.esapi.ESAPI class. Tomcat 10 does not support this anymore since moving to the jakarta servlet api 5.x.

**Comment by kwwall** [comment]
I just downloaded the Jakarta version of the ESAPI 2.6.0.0 jar from https://repo1.maven.org/maven2/org/owasp/esapi/esapi/2.6.0.0/esapi-2.6.0.0-jakarta.jar, extracted 'org/owasp/esapi/ESAPI.class', and ran this:
```bash
$ javap ESAPI.class
Compiled from "ESAPI.java"
public final class org.owasp.esapi.ESAPI {
  public static void clearCurrent();
  public static jakarta.servlet.http.HttpServletRequest currentRequest();
  public static jakarta.servlet.http.HttpServletResponse currentResponse();
  public static org.owasp.esapi.AccessController accessController();
  public static org.owasp.esapi.Authenticator authenticator();
  public static org.owasp.esapi.Encoder encoder();
  public static org.owasp.esapi.Encryptor encryptor();
  public static org.owasp.esapi.Executor executor();
  public static org.owasp.esapi.HTTPUtilities httpUtilities();
  public static org.owasp.esapi.IntrusionDetector intrusionDetector();
  public static org.owasp.esapi.Logger getLogger(java.lang.Class);
  public static org.owasp.esapi.Logger getLogger(java.lang.String);
  public static org.owasp.esapi.Logger log();
  public static org.owasp.esapi.Randomizer randomizer();
  public static org.owasp.esapi.SecurityConfiguration securityConfiguration();
  public static org.owasp.esapi.Validator validator();
  public static java.lang.String initialize(java.lang.String);
  public static void override(org.owasp.esapi.SecurityConfiguration);
  static {};
}
```
Note the references to:
```java
 public static jakarta.servlet.http.HttpServletRequest currentRequest();
 public static jakarta.servlet.http.HttpServletResponse currentResponse();
```

If you have further evidence that something is awry, than reply and add a comment, but until then, I am closing this issue and assuming your problem exists simply because you did not specify `jakarta` as the **classifier** attribute value.
