### ISSUE TITLE
SafeString validation.properties error on parsing \.

### ISSUE THREAD

**Issue by meg23** [ESAPI/esapi-java-legacy#92]
_From [caugh...@gmail.com](https://code.google.com/u/110385687538743415675/) on December 17, 2009 13:21:22_

GetInputValidation takes regular expression called SafeString.
Throws exception in parsing a simple regex.
Regular expression in the .properties file (validation.properties) contains
"." What steps will reproduce the problem? 1. create a new dynamic web project in eclipse, create new java file with
main(..) method
1. importcommons-fileupload-1.2.jar, commons-logging.jar,
   ESAPI-2.0-rc2.jar, log4j-1.2.15.jar in WEB-INF/lib
2. Add following code in main method
       try {
           Validator instESAPI = ESAPI.validator();
           instESAPI.getValidInput("address","55 main st. pasadena ak",
   "SafeString", 512, false);
       } catch (ValidationException ve) {
           ve.printStackTrace();
       } catch (IntrusionException ie) {
           ie.printStackTrace();
       } catch (Exception e) {
           e.printStackTrace();
       }
3. run as Java application What is the expected output? What do you see instead? Expected out: no error is expected
   What do I see instead: Following error
   org.owasp.esapi.errors.ValidationException: address: Invalid input. Please
   conform to regex ^[p{L}p{N}.]{0,1024}$ with a maximum length of 512 What version of the product are you using? On what operating system? Windows XP SP3 operating system, JDK 1.5, I tried both ESAPI-2.0-rc2.jar
   and ESAPI-2.0-rc4.jar, same error.

_Original issue: http://code.google.com/p/owasp-esapi-java/issues/detail?id=82_

**Comment by adityarajverma** [comment]
> _From [chrisisbeef](https://code.google.com/u/chrisisbeef/) on December 17, 2009 14:52:23_
> 
> This is due to not accounting for spaces in the SafeString regex.
> 
> Using the regex ^[.\p{Alnum}\p{Space}]{0,1024}$ resolves the issue. Also condensing
> into \p{Alnum} requires a single CharClass lookup where \p{L}\p{N} requires 2.
> 
> Committing the fix to trunk for ESAPI4J 2.0
> 
> **Status:** Accepted

what type of regex is this .^[.\p{Alnum}\p{Space}]{0,1024}$

i am not able to use it.How you use it .It gives wrong rege x error on ESAPI.peroperties file

**Comment by kwwall** [comment]
@adityarajverma You are missing some critical '\\' characters. It needs to be '\\\\p' for both cases in your validation.properties (or ESAPI.properties) file.

This is from `configuration/esapi/validation.properties`
:
`Validator.SafeString=^[.\\p{Alnum}\\p{Space}]{0,1024}$`

**Comment by adityarajverma** [comment]
> @adityarajverma You are missing some critical '\' characters. It needs to be '\\p' for both cases in your validation.properties (or ESAPI.properties) file.
> 
> This is from `configuration/esapi/validation.properties`
> :
> `Validator.SafeString=^[.\\p{Alnum}\\p{Space}]{0,1024}$`

@kwwall   Thanks a lot .It worked for me.One more question ,how we can load validation.properties file.I always need to define in ESAPI.properties file.I created one validation.properties file but no regex is picked from there.code always give error type not foound in ESAPI.properties file.

So on last i need to set in ESAPI.properties file.

Thanks a lot for your quick help.

**Comment by kwwall** [comment]
In ESAPI.properties, define the property
               Validator.ConfigurationFile=validator.properties

And then drop the 'validator.properties' file in the same place where your
ESAPI.properties is found. That should do it for you and allow you to move
your "Validator.SafeString" property to your separate
'validator.properties' file.

There are other ways to make this work, but that is probably the simplest.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.
